### ISSUE TITLE
Merchant Reference in Adyen

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#108]
## Question

Is it possible that the merchant reference is wrong in some cases? 
For example for these PSP Reference numbers:
4635378937291611, 1635378935190829, 4735387251334500, 4335468561589597, 4345480591855391
If its not correct in Adyen, can you please solve this issue?

If its correct, please tell us how we can match the other key or id with the reservation_id in Apaleo.

## Background

We are currently working on the data we receive from Adyen for our Accounting Department. Our Accounting needs the information which Payment was in the end successful and which wasnt. We realised that the Apaleo reservation_id is mentioned as the Merchant Reference. But in some cases we identified that there is another key or id instead of the reservation_id. We identified that this is the case for bookings that are coming via IBE. For some transactions that are coming via IBE the reservation_id is provided and for some its the other key.

**Comment by randyrod** [comment]
Hi,

We introduced the use of the `reservation_id` as the psp reference in December 2018, and before this the psp reference was the choice of the clients to determine.

For instance, the payment with the PSP Reference `1635378935190829` was received on `2018-09-25` and by that date we still did not have in use the reservation_id as the reference.

One way to get the related reservation for that psp reference, is to use the PSP Reference to find the related folio.

**Comment by patrickHermannLimeHouse** [comment]
Thanks for the update. 
I have one more follow-up question on this. For the authorised or refused transactions, we still don't have the reservation_id in Merchant reference, for example, PSP reference: 4725542212211609 or 4535542391527619. These transaction examples are recent. 
Is it intended behaviour?

**Comment by randyrod** [comment]
Hi,

For these transactions, we tried to tokenise the credit cards we received from booking.com. For instance, 4725542212211609 the story is the following.

We received the reservation from booking.com and validated the credit card received for this purpose we used the booking number sent by booking.com. In this case, the credit card was invalid because the guest provided the wrong expiry date. As we marked the credit card as invalid in booking.com, this triggers an email to the guest to update his credit card. Then the guest proceeded to update his credit card 4 hours later with the correct expiry date, and the valid credit card was then stored into the reservation and apaleo automatically captured the outstanding amount.

As those transactions are only validity checks with no amount, they are not relevant for accounting.

If you have further questions, feel free to contact us.

Regards,
Randy
