### ISSUE TITLE
Account and target not provided when requesting the secure URL

### ISSUE THREAD

**Issue by dbajet** [apaleo/api#124]
## Question

In the picture under *security* in  https://blog.apaleo.com/developer/ui-integration-guide, the Integration Service, when requesting a secure URL, is supposed to provide the target and the account.

Assuming this is not the case (I don't receive them), how do we know which target and, more importantly, which account is served?

Should we assume that if the `propertyId` or the `reservationId` is not provided then we are at the account level?

**Comment by pgrm** [comment]
hello @dbajet 

yes, the picture on the guide is a bit misleading, I'll update it. The idea is that you register a link specific per account and integration target, and we call back this link. Hence all the information you need is within this link, that's how we "provide it to you". But we don't do it explicitly. I'll clarify this part in the guide next week.

---------------

> Should we assume that if the propertyId or the reservationId is not provided then we are at the account level?

Yes and no. As mentioned above, you should register different endpoints for different targets + accounts. There are some targets, which, if rendered, don't provide any ID, because there isn't any ID which could be provided. Those are (and will be) the targets on account level. For now, we have only the account dashboard on the account level. In the future I guess there will be also some menu-point targets for the account level, these also won't provide any additional ID to the iframe source URL.

--------

I hope that clarifies everything. If you are missing some target, just let me know and I'll check if we can add them.

**Comment by dbajet** [comment]
Thank you @pgrm 
This is perfectly clear (and I have been able to correctly integrate :-) ).
