### ISSUE TITLE
invoice address

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#137]
## Question

I'm little bit confused. The invoice address is blank. 
How will the invoice address filled, when I create a new reservation?
Is the invoice address automatically the address from the booker?
When I update the invoice address at the folios, the booker doesn't change.

Is there a possibility to receive the invoice address with **v1/reservation/{id}?extend=booker**
For now there is no extension. Do I have to make a second api call for the folios and use the receiving address as invoice address for the reservation?

## Background

I want to get the invoice address when I receive a reservation.
So the guest can update it's address during the checkout.

**Comment by andreastubbe** [comment]
Booker, guest and invoice recipient can be three different people, with three different addresses.
The invoice address is taken from the folio-debitor. It is initialised with the booker, but not updated later, when you change the booker. Otherwise we'd need some data merging-overwriting-rules-magic.

In the apaleo UI, we allow users to choose between:
- any of the guest's addresses
- the booker address
- *new* whether the invoice should be created for the associated company (this is so new that it's not even documented yet)

Then, use the data to PATCH the folio, and create the invoice.

**Comment by c2ofh** [comment]
Thank you Andrea,

so I will fetch the folios with the reservation and take the invoice address from the folio.
