### ISSUE TITLE
assign-unit assigns occupied room

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#138]
`Apaleo-Tracking-Id`: not present

**Issue**

We want to assign automatically a room to a reservation via
PUT "booking/v1/reservation-actions/{reservation_id}/assign-unit"

**Expected behavior:**

One of the free rooms will be assigned.

**Actual behavior:**

The assigned room was still occupied.

**Comment by pgrm** [comment]
@c2ofh automatic assignment considers if the room will be occupied during the time the reservation is expected to be in house. This means, if you do an automatic assignment for a reservation with arrival tomorrow, you might get a room assigned, which is occupied right now, with a reservation, which has a departure today or tomorrow.

Is this the behavior you see? Because that would be expected behavior.

**Comment by JanJanssenD** [comment]
I have related problem:

First i call "booking/v1/reservation-actions/{$reservation_id}/assign-unit" and immediately thereafter i call "/booking/v1/reservation-actions/{$reservationId}/checkin". The basic idea is, that we assign a room at the time of checkin.

**Expectation:**
We can checkin in the assigned room. 

**But:**
"The assigned unit with id * is currently still occupied."

**Comment by swiesener** [comment]
Could be that the unit is still assigned to another reservation with status in-house. Maybe that is an old reservation which was forgotten to be checked-out.

You can still assign this unit to another reservation as long as the other reservation is confirmed only and not in status checked-in yet. You get the error when you try to check-in the reservation.

In order to avoid old reservations dangling around in status checked-in, you might go to property settings and toggle automated check-out.
