### ISSUE TITLE
Pushing Rate Updates to Correct Property

### ISSUE THREAD

**Issue by YouJinTou** [apaleo/api#153]
## Question

I have to push many price updates for a given property. I'm using https://api.apaleo.com/swagger/#!/Rate/RateplanRate_plansByIdRatesPut to do that. How can I be sure I'm pushing for the correct property? What if property A and property B both have the same rate plan IDs?

**Comment by randyrod** [comment]
Hi @YouJinTou,

Thanks for your message.

In order to understand the answer there is something important to know.

The relationship between a property and a rate plan is a one to one. So A rate plan will always belong to a property. Which means that when updating the rates for a rate plan, means that you are updating directly to a rate belonging to a rate plan that belongs to a single property.

Rates are identified by the `from` and `to` properties, based on the rateplan.

For instance of you do a PUT request to update a rate:
`PUT /rateplan/v1/rate-plans/{id}/rates`
with the following payload:
```
{
  "rates": [
    {
      "from": "2019-06-11T17:00:00+02:00",
      "to": "2019-06-12T11:00:00+02:00",
      "price": {
        "amount": 123.5,
        "currency": "EUR"
      },
      "restrictions": {
        "minLengthOfStay": 1,
        "maxLengthOfStay": 30,
        "closed": false,
        "closedOnArrival": true,
        "closedOnDeparture": true
      }
    }
  ]
}
```
The `Id` on the URL must be that of the rate plan that contains the `rate` that you want to update.

The payload means that the rate that will be updated is the one 
```
      "from": "2019-06-11T17:00:00+02:00",
      "to": "2019-06-12T11:00:00+02:00"
```

If you want to know to which property this rateplan belongs to, you can easily make a request to:
`GET /rateplan/v1/rate-plans/{id}` and get the propertyId from the response body.

I hope that the information is helpful, if you have further questions feel free to let us know.

Regards,
Randy
