### ISSUE TITLE
Expected behavior of GET /rateplan/v1/services after deprecation of includeOnlySoldViaDirectChannel

### ISSUE THREAD

**Issue by msmeza** [apaleo/api#165]
## Question

What services are expected to be returned by the endpoint `https://api.apaleo.com/rateplan/v1/services?propertyId=[PROPERTY_ID]` once the parameter `includeOnlySoldViaDirectChannel` is deprecated?

## Background

Currently, the definition of `includeOnlySoldViaDirectChannel` states: "Include services that can only be sold via the direct channel. Otherwise, results are limited to the services that can be sold on all channels". Once this parameter is removed, what services are expected to be returned if no channel codes are specified? All services? Services that can only be sold through all channels?

The reason I ask this question is because, even now, the services returned seem to be inconsistent. For example, in our test property "BER" we have five services, three of which can be sold through all channels, one that can be sold through "Direct" and "Ibe" and one that can only be sold through "Direct". If I call the endpoint `https://api.apaleo.com/rateplan/v1/services?propertyId=BER` I get four services, the three that can be sold through all channels and the one that can be sold through "Direct" and "Ibe", but this seems to go against the stated definition, as I expected only three services to be returned. Why are four services returned? Will this continue to be the behavior once `includeOnlySoldViaDirectChannel` is deprecated?

**Comment by dario-hd** [comment]
Hi @msmeza, I know that the flag and the documentation could be a bit misleading but, based your setup, the behavior is correct. So basically, the flag was introduced in order to exclude services sold **only** via `Direct` channel.

Once the deprecation period is over, all services will be returned. You can then use the `channelCodes` to filter them out. This filter works like the `channelCodes` filter in the rate plan API, meaning that it will return services that are sold through **any** of the specified channels.

The `includeOnlySoldViaDirectChannel` was used before we introduced the new service offers APIs. Would be cool to understand more about your use case, why do you need to use such filter?

**Comment by msmeza** [comment]
We don't really need the filter, quite the opposite, actually: what we need is to get all services for a property, but in order to do so today we need to either set `includeOnlySoldViaDirectChannel` to true or to list all channel codes in `channelCodes`. Based on what you said, once `includeOnlySoldViaDirectChannel` is removed, we can simply call the endpoint with only the property ID to get the same result, right?

**Comment by dario-hd** [comment]
Exactly!

**Comment by msmeza** [comment]
Excellent! then we know exactly what to expect.

Thank you for your help!

**Comment by dario-hd** [comment]
You are very welcome!
