### ISSUE TITLE
retrieving subscriptions

### ISSUE THREAD

**Issue by BrunoStardekk** [apaleo/api#169]
Im trying to get the subscriptions via the https://webhook.apaleo.com/v1/subscriptions endpoint but I keep getting a 403 forbidden. I already should have the "notifications:subscriptions.manage" scope but if I dont could this be added?

Our client id: stardekk-connect

If this isnt the problem here is de tracking ID if that would be needed: trackingid: 0HLNJU18P3P1N:00000001

Thanks

**Comment by mri-apaleo** [comment]
I checked the logs and the config. You have the appropriate scopes. Based on the logs I got the info that the Bearer and ApaleoHeader were forbidden, so we will do some investigation.

**Comment by mri-apaleo** [comment]
@BrunoStardekk: Could you send over your Jwt token via email to support@apaleo.com

**Comment by pgrm** [comment]
hello @BrunoStardekk 

so to clarify, based on your email to support, you can currently only retrieve / delete subscriptions with the same client you created them, that's why the swagger UI requires you to provide client-id + secret. But if you have a connect client, those don't work in the swagger UI. We are working on fixing that issue, to make it easier in the future.

You have currently 3 subscriptions:

- 1 for the account JTDS, Property BER
- 2 for the account QOYX, properties:
  - HALLO
  - STARDEKKEL

which of those should we deactivate?

**Comment by BrunoStardekk** [comment]
All 3 please

**Comment by pgrm** [comment]
@BrunoStardekk I've removed all 3 subscriptions, any webhooks which were in transit until now, will continue to be tried to be re-delivered for up to 24h
