### ISSUE TITLE
Authorization best practices

### ISSUE THREAD

**Issue by msmeza** [apaleo/api#17]
## Question

We're in the process of integrating with your API and we wonder whether you have any recommendations in terms of authorization best practices. It's clear it's not a good idea to get a new access token every time a call will be made to the API, but other than that, do you have any preferences/recommendations in terms of how often a new token should be generated, or in terms of the number of active tokens at any given time for a certain property?

## Background

Our integration will consist of various components, which at some point or another will need to call Apaleo's API. Is it acceptable for each of these components to get their own token at the beginning of their run (which would be used for the duration of said run), even though this could lead to the existence of multiple active tokens at a given time, if two or more of these components run at the same time? Perhaps you prefer it that a single token is active for a given property at all times, and that all components use the same token?

**Comment by pgrm** [comment]
Hey @msmeza,

I've seen already both extremes from other partners.

The problem, when you'll request a new token for every single call is simply, that it's slow. You'll basically have twice as many requests to our service with the same latency, ... It will work, but it will be much slower for you, and also quite tough on our identity server, so I appreciate that this wasn't your first choice.

The other extreme, when you try to overshare the token, persisting it in a database etc., it usually introduces a lot of complexity in the system with very little benefit.

## How we do it ...

We are sharing tokens with a simple in memory cache. Different instances (processes) of our application have different tokens. One process usually reuses the same token. However, due to concurrent requests, 2 (or more) tokens might exist at the same time on one process. We care about sparing the call to the identity server, but not at the cost of too much added complexity.

If you already have a distributed or centralized cache in place you can also use that to share the tokens.

## One tokens per component ...

I'm not entirely sure what a component is in your context, but it sounds very reasonable to share a token per account and component if that is easier for you.

However, please keep in mind, that the token has an expiration time and you want to stop using it shortly before it expires, since our clocks probably aren't perfectly synchronized.

I hope that answered all your questions. Please let me know, in case something else is missing.

**Comment by msmeza** [comment]
Thank you for your reply, @pgrm!

Yes, I think your answered pretty much covered everything.

A component in our context is a micro service with a single purpose (collecting reservation information, collecting billing data, etc.)

**Comment by pgrm** [comment]
in that case @msmeza, as I said - share the token as much as you can, as long as it's convenient within that micro service (like we do as well), that will repay after the first request reusing the token. 

However, you don't have to go through any hassle to have a global token for your whole system.
