### ISSUE TITLE
payment questions 

### ISSUE THREAD

**Issue by SimonBigelmayr** [apaleo/api#185]
## Question

while reviewing the API description (https://api.apaleo.com/swagger/) a few questions regarding the payment have arisen:

1) How do we retrieve all items related to a reservation? (e.g. 1x breakfast, 2x overnight stay etc.). When I retrieve folios, I only see the total amount and not the single items.

2) How can I retrieve the guest's billing address?

2) How do I pay? We would like to make the payment ourselves and then put a negative charge on the reservation. Is this call the right one?

3) if the balance of a booking is 0, can this booking be checked out? Or do previous calls/examinations have to be carried out?

**Comment by randyrod** [comment]
Hey @SimonBigelmayr,

We have a very nice guide showing an example of a guest journey that might answer some of your questions in this ticket: https://blog.apaleo.com/developer/digital-guest-journey-with-apaleo

Here are the answers to your questions:

> 1. How do we retrieve all items related to a reservation? (e.g. 1x breakfast, 2x overnight stay etc.). When I retrieve folios, I only see the total amount and not the single items.

In order to retrieve the services for a specific reservation, you can make a request to `GET /booking/v1/reservations/{id}/services` to the apaleo API.

> 2. How can I retrieve the guest's billing address?

The answer to this one is included in the guide, you can retrieve the information from `GET /booking/v1/bookings/{id}` in addition you can retrieve it from the Folio if it exists `GET /finance/v1/folios/{id}`.

You would get the information you are looking for in `primaryGuest.Address` or `booker.address`

Moreover, as stated in the guide, you can update such billing address with `PATCH /finance/v1/folios/{id}`

> 3. How do I pay? We would like to make the payment ourselves and then put a negative charge on the reservation. Is this call the right one?

In order to perform manual payments you can call `POST /finance/v1/payment-tasks`. Regarding putting a negative charge, once the payment is through and validated, the amount on the folio will be automatically updated. You can take a look at the multiple options you have in the apaleo API for payments here `https://api.apaleo.com/swagger/#/FolioActions`, here `https://api.apaleo.com/swagger/#/Payment` and here `https://api.apaleo.com/swagger/#/PaymentTask`

> 4. if the balance of a booking is 0, can this booking be checked out? Or do previous calls/examinations have to be carried out?

In general, if the balance is 0, which would mean that all the charges have been posted and dully paid. You can check out with no issues. However, you can take a look at this guide, showing a nice check out checklist to make sure that everything is on point https://apaleo.zendesk.com/hc/en-us/articles/360000910272-The-Ultimate-Check-Out-Checklist

I hope this information is helpful. If you have further questions, please let us know.

Regards,
Randy

**Comment by SimonBigelmayr** [comment]
Hey Randy, thanks for the quick answers. 👍  
I forgot to ask the following:

5. How is a private/business invoices handled? I can see "isMainFolio", is this referring to private or business or is it something totally different?

6. Is it possible to add a payment to a booking that is not checked in yet?

**Comment by randyrod** [comment]
Hey Simon,

Sure no problem.

> 5. How is a private/business invoices handled? I can see "isMainFolio", is this referring to private or business or is it something totally different?

So for the first part of the question, a private or business invoice only differ in the fact that the business invoice is addressed to the company, and not the guest/booker. Also, you can set up if you can check out on AR for a specific company or not.

Now `IsMainFolio` is just a flag that tells you that it is the first folio of the reservation, which was created with the reservation, the main highlights of this folio are that it cannot be deleted and it is the only folio that can have unposted charges.

> 6. Is it possible to add a payment to a booking that is not checked in yet?

In most cases it should be possible to add a payment for a folio/booking. In order to see the possible actions that you can perform on a folio you can make a call to: `GET /finance/v1/folios/{id}` for a specific folio, or to `/finance/v1/folios?reservationIds={ReservationId}&pageNumber=1&pageSize=100&expand=allowedActions` to get the list of folios, making sure that for the latest you provide the parameter `expand=allowedActions`.

The response should have the array `allowedActions` which contains all the possible actions that you can perform on the folio like this:
```
"allowedActions": [
        "ChangeAddress",
        "AddCharge",
        "AddCancellationFee",
        "AddNoShowFee",
        "AddPayment"
      ]
```

**Comment by SimonBigelmayr** [comment]
>So for the first part of the question, a private or business invoice only differ in the fact that the business invoice is addressed to the company, and not the guest/booker. Also, you can set up if you can check out on AR for a specific company or not.

Does this mean, that we have to compare the guest-name with the name on the invoice to find out if the folio is a private or business folio or is there any other way?

**Comment by randyrod** [comment]
No, I wouldn't consider that your best choice.

I would recommend the following course of action.

1. Make a request to `GET /booking/v1/reservations/{id}`
2. Check whether the response has the property `company` set. If it is set, then the reservation was created on behalf of a business. Otherwise it is a "private" booking.

A sample response of the `company` property looks like this: 
```
...
"company": {
    "id": "MUC-UMBRELLA",
    "code": "UMBRELLA",
    "name": "Umbrella Corp.",
    "canCheckOutOnAr": false
  },
...
```

**Comment by SimonBigelmayr** [comment]
I am mostly concerned about a case where a reservation has some items that belong to a business folio/invoice and some to a private folio/invoice. 
Our current logic requires a way to see which folio is the private and which is the business folio that later in the checkout process will be "converted" to a private and business invoice (or multiple private and business invoices).

Is it right that the "Accommodation" will always be one the mainFolio? Thus, if a reservation has a company model attached this will normally be the business folio and the other folio(s) will be private? Is that right form a business logic perspective?

**Comment by randyrod** [comment]
HI @SimonBigelmayr,

There is no such difference like private/business folios in apaleo. The decision of which one will be private/business is done at the invoice creation level.

Regarding the second remark about the "Accommodation" that is not the best assumption. It doesn't matter if the folio is the first or the tenth, that does not mean that it is private/business. There can be other folios in the reservation, that are still considered to be for a business and not a private guest.

**Comment by SimonBigelmayr** [comment]
- Why is it not possible to move the accommodation and breakfast item from folio ZWTABLUS-1-1 to ZWTABLUS-1-2? Or split them into two folios?
- is there something like a required preauth amount for a reservation? Some other PMS have that value and want the guest to block a certain amount on the credit card as security
- why don’t we receive a notification if room status changed from dirty to clean if the room is assigned to a reservation?
