### ISSUE TITLE
Subscription ARI notifications

### ISSUE THREAD

**Issue by BobPurple** [apaleo/api#188]
We subscribed for ARI notification on 3 different accounts.

One of them is the only one enabled for the OAuth management but we are not receiving any notifications from it. Can you please tell us why?

Here is the subscription, but we don't receive any notification:

{
  "subscriptions": [
    {
      "id": "EDM1QVL1",
      "propertyId": "222",
      "channelCode": "ChannelManager",
      "endpointUrl": "https://apitest.roomcloud.net/be/xml/Apaleo.jsp?Id=424",
      "fullSyncPeriod": "PT90M",
      "deltaSyncPeriod": "PT1M",
      "ratePlanIds": [
        "222-777",
        "222-FULL_BOARD"
      ],
      "numberOfDays": 365,
      "enabled": true
    }
  ]

}

We removed restrictions in all rate plans. 

Thanks!

**Comment by ozonni** [comment]
@BobPurple sorry for a late response. Actually you found a bug. Due to over night time slice definition setup from 03:00am - 02:01am and time shift happening next year in Spring, we have an issue with generating time slices. It's already in back log and we are gonna fix it next. As a workaround, you can create new time slice definition e.g. 3pm-12pm and create new rate plans and create subscription for them.
