### ISSUE TITLE
expand vat_type for /finance/v1/folios/#id

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#201]
## I want

An expand method for GET /finance/v1/folios/#id
Currently you just get the vat_type, for example "reduced", but not the value itself.
It would be great, to extend the request by vat_type, to get also the information 7% for example.

## Use cases

We want to show the folio positions with its values before the check-out, if everything is okay, we can trigger the invoice creation.

## What I do

Currently I get the folios by GET /finance/v1/folios/
Then I ask for the positions for each folio via GET /finance/v1/folios/#id
Then I have to do another request to get the vat_types and merge the types with the previous response.

Due to the new api rate limit I want to do reduce the amount of requests.

**Comment by mri-apaleo** [comment]
This is a good point and I created an issue for it in our backlog.

The team will get back to you once it's prioritized.

**Comment by andreastubbe** [comment]
Hi @c2ofh ,
This will take some time to build. Reason is that we share the model for money-with-VAT fields across the entire API. Because consistency matters. The new model would look like this:
```
{
   gross: required,
   net: required,
   currency: required,
   VAT: optional { <== because not everything is subject to VAT
       type: required,
       percent: required
   }
}
```
This is unfortunately a breaking change, which makes it way more complicated to roll out. Still makes sense, but... time.

Here's a workaround until then:
The VAT types are fairly stable. Hotels cannot change those themselves - apaleo brings them out of the box. Meaning, they only change if a state decides to change their VAT. That makes them very cacheable!
So, instead of requesting & merging after each call, you could get them on initialising (as part of the connect flow, for example), and then again each morning or midnight.
