### ISSUE TITLE
City tax

### ISSUE THREAD

**Issue by oluyoung** [apaleo/api#205]
## Question

In the Apaleo dashboard, under Settings > Distribution page there is the option to enable city tax.
When the city tax is enabled, what endpoint do we make a request to so it is factored in and we can calculate it along with the VAT.

## Background

We are working with the UP IBE booking engine.

**Comment by andreastubbe** [comment]
At the moment, city tax is only added **on check-in**, when you set the flag in the call. We are working on some new features there, so watch https://github.com/apaleo/announcements for updates.

- include the city tax in the offer & reservation response, so that you can display it on the IBE
- add city tax on reservation creation. This will happen automatically, depending on a configuration option of the hotel
