### ISSUE TITLE
Inconsistent internet booking engines

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#207]
With `GET booking/v1/types/sources` I receive a nice looking list of all booking engines, included "**Booking.com**".

When I create a reservation with this mentioned channel, I get **BookingCom** as channelcode.

Would it be a problem, when you return an Object for each IBE?
```ruby
{name: "Booking.com", code: "BookingCom"}
```
Or can you tell me the rules to convert the name to the code?

Now I fixed it on my side, but I think this is not very good.
Reservation response will be saved in lowercase. => 'bookingcom'
In the sources list, I remove spaces and dots for each source and transform it also to lowercase, to get a matching.

**Comment by ozonni** [comment]
@c2ofh there are two different things, channel and the source. When you create reservation, first you specify the channel and it's a enum value. If it's Direct or IBE or BookingCom then you don't need to specify the source. But if it's ChannelManager then you have to set the source, to know the origin of the reservation. In this case the source should be one from that list (https://api.apaleo.com/booking/v1/types/sources). Sources are pre-defined and most probably you need to map them on your side. Because e.g. some might write 'Booking.com' or 'BookingCom' or 'Booking Dot Com'.

https://api.apaleo.com/swagger/#!/Booking/BookingBookingsPost

![image](https://user-images.githubusercontent.com/25206121/64690959-f78bee00-d491-11e9-9d63-50be12d3b961.png)

**Comment by c2ofh** [comment]
Today I had again the problem. The source in sources is "HNS OnePageBooking"
In the reservation the source is 'hns onepagebooking'. Was there a change in the response?

I've mapped the Names to downcase, removed spaces and dots. 
Now the source couldn't be matched, cause the name was written with space. It would be really helpful to get the in sources also the name, how you show it in the reservation response.

@ozonni is there something planed?
