### ISSUE TITLE
ReplaceRateModel ->price "optional" results in errors

### ISSUE THREAD

**Issue by t-haze** [apaleo/api#209]
## Question

Dear DEV-Team, 

documentation for PUT /rateplan/v1/rate-plans/{id}/rates request describes _price_ inside _ReplaceRateModel_ as **optional**. Whenever i do not transmit price object at all, it results in an 422 error "Cannot set restrictions on a rate with no price". Whenever i do transmit price, but as an empty object, it results in a 422 error ""rates[0].price: Cannot deserialize the current JSON array".

Is it possible to update only restrictions with PUT rates request, without re-sending prices?

Best regards,
Tobi

**Comment by dario-hd** [comment]
If you want to use the PUT endpoint, you have to set all the required fields.

If you want to set the same restrictions for all the rates in a given time range, you can use the PATCH endpoint.

Here's an example:

```
curl -X PATCH --header 'Content-Type: application/json-patch+json' --header 'Authorization: Bearer YOURTOKEN' -d '[{ \ 
   "op": "replace", \ 
   "path": "/restrictions", \ 
   "value": { \ 
     "minLengthOfStay": 2, \
     "maxLengthOfStay": 30, \
     "closed": true,  \ 
     "closedOnArrival": false, \ 
     "closedOnDeparture": false \ 
   } \ 
 }]' 'https://api.apaleo.com/rateplan/v1/rates?ratePlanIds=MUC-NONREF_SGL&from=2019-10-10&to=2019-10-11'
```

**Comment by t-haze** [comment]
Alright, i was aware of the PATCH method.
Just wondered if it IS possible to achieve the same with the PUT method, as the price object (as i described in the post) is stated as **optional** inside our documentation **= NOT required** as you wrote.

**Comment by bennetone** [comment]
Hi @t-haze 

for derived rate plans the price cannot be set, as the price is calculated based on the pricing rule of the rate plan.

For base rate plans you can either provide an empty rate with only _from_ and _to_ defined. This will remove the price and all restrictions for that night and the rate plan will not be available for that night.

If you want to set restrictions, then the rate has to be initialized for this day, which means it has to have a price set. With the PUT endpoint you need to send the data for all properties of the resource, otherwise it means you want to remove them.

To answer your question: you can achieve the same with the PUT, but then you would need to execute the PATCH on your side. The flow is to GET all rates first, change what you want to change and the send back all with the PUT. This is also described in the [Revenue Management Integration Guide](https://blog.apaleo.com/developer/rms-integration-guide).

![image](https://user-images.githubusercontent.com/25197867/65231018-35f75d80-dacf-11e9-948b-cde3346599e8.png)
