### ISSUE TITLE
Cannot PUT to ReservationDetailsTab

### ISSUE THREAD

**Issue by koskiOvaa** [apaleo/api#213]
`Apaleo-Tracking-Id`: Didn't get any.  Request was done at Sep 23 21:58:01 +02:00

**Code**
422

**Expected behavior:**

Excepting to get a correct reply. At least expecting to understand the error message :)

**Actual behavior:**

Received reply:

{"messages":["ErrorMessage: Received expiration date is lower than current UTC time - ErrorContent: Received date 09/23/2019 19:59:01 - Current UTC 09/23/2019 19:58:01"]}

**Related Issues:**

No.

**Comment by koskiOvaa** [comment]
So the received date (not sure where it comes from) seems to be in the future according to the current UTC time, but I get that error. Anything I can do?

**Comment by andreastubbe** [comment]
The tracking ID is `0HLPNC5OC7M1B:00000001|28d5f97d68d9` (this will make it easier to find your call again).

What we do when you register a private UI integration, is check for syntactic validity (you passed that), and then call that specified URL. Now, unless I'm mistaken, this call is returning and error, and we don't do much but passing the result on to you.

Have you tried calling the URL you pass directly, and does this work?

**Comment by koskiOvaa** [comment]
Yes. I have tried to call the URL directly and all worked.

And now also the PUT call works. I increased the expTimestamp to be 1 hour in the future, not one minute I returned before.

**Comment by koskiOvaa** [comment]
So this can be closed if you want, but I still don't understand the reply I got when doing:

PUT https://integration.apaleo.com/integration/v1/ui-integrations/ReservationDetailsTab

Reply: 
{"messages":["ErrorMessage: Received expiration date is lower than current UTC time - ErrorContent: Received date 09/23/2019 19:59:01 - Current UTC 09/23/2019 19:58:01"]}

But the received date is higher than the current UTC, right?

**Comment by andreastubbe** [comment]
Yeah, odd! We'll check more tomorrow, thanks for reporting and glad you could work around it.

**Comment by pgrm** [comment]
@koskiOvaa I'm sorry, the error message really is confusing. We're actually adding 1 extra minute to the expiration time, to make sure that the UI will have enough time to render the iframe.

Why do we do that? Because the whole process might take a while, because we're also requesting other UI integrations at the same time and then the UI gets the response and needs to process it. Also the UI clock is usually less accurate than the server clock. So 1 minute is a bit border line and we're checking for having more than a minute left over.

That said, the current error message is completely misleading for your use case and we'll fix that first thing tomorrow morning.

Please add an extra minute to your expiration time, everything should work afterwards 🤞

**Comment by randyrod** [comment]
Hi @koskiOvaa thanks for reporting this, we have updated the error message to a more user friendly text.

I will be closing this issue now. Thanks again :)
