### ISSUE TITLE
Get the user's authorisation with different redirect_uri for each one

### ISSUE THREAD

**Issue by ikrav4ic** [apaleo/api#228]
## Question

We try to integrate our system with apaleo.
We've tried to use our API credentials to connect user from his workflow and find the problem at the getting user authorization step.

## Background

In the authorize url I need to send the redirect_uri parameter.
I understand that this parameter has that value, which I sent before to get API credentials.
The problem we have, that each user will have his own redirect_uri (for ex. site1.hkeeper.us/pms/apaleo, site2.hkeeper.us/pms/apaleo)
How can we solve this problem?

**Comment by bennetone** [comment]
Hello @ikrav4ic,

when I understand correctly then the hotel customer for your housekeeping app each do have a login on their own domain, similar like the workspaces for Slack, right?

In such a case you would have to run a service on a generic domain like e.g. https://apaleo.hkeeper.us which presents the user with a website asking if they already have an account with you or not. From there you can navigate the ones without account to your signup page and the others should enter their customer id (e.g. site1). Then you will direct them through the OAuth Flow to receive the authorization code. This redirect URL also needs to be generic, e.g. https://apaleo.hkeeper.us/callback. Then you need to store the authorization code you received for the customer site1 for any server to server communication between your app and apaleo for this specific customer.

OAuth2 requires the redirect URL to be configured on the identity server per API client, so that nobody can run the authorization flow with leaked API client credentials and get an authorization code delivered to a non-trustful app.

Please read the [guide for the authorization](https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0) to get more details on the flow.

Regards,
@bennetone
