### ISSUE TITLE
Get response as invalid client on step 2

### ISSUE THREAD

**Issue by ikrav4ic** [apaleo/api#232]
## Question
I try to exchange the authorization code for an access token
but as a result, I've get invalid user message
Where can be a mistake from my side
Here is the code
https://c2n.me/44nz8Ae

**Comment by ikrav4ic** [comment]
The problem with error fix
but in response I've got empty string
no access token

**Comment by WinniX** [comment]
Hello Igor,

Sorry for the delay. It looks like the issue is that you are trying to use the same authorization code multiple times, which is incorrect. The thing is that the authorization code is designed as a one time code that should be used to exchange it for the access token. Please try to obtain new authorization code and as you get it, exchange it for the access token. This should help. 

Best regards,
Eugene / apaleo Team

**Comment by ikrav4ic** [comment]
Hi
Now I've got an empty string as a response.
No access token
My client id HKeeperConnect
Last authorization code - 78fcf7b746c37df25c12ad9bf17afa20c931a350f3dc9c8ca4f60e4c65cba761
Please look in the logs

**Comment by WinniX** [comment]
Hello Igor,

This is weird that you are getting an empty response. I noticed that you are trying to implement the OAuth authentication flow yourself. To be honest, the protocol can be tricky to implement from the scratch. The best practice here is using an external library which already contains the OAuth logic flow, so you will only need to set the parameters. Here you can find the recommended libraries for PHP https://oauth.net/code/php/

Hope this will help!

Best regards,
Eugene / apaleo Team
