### ISSUE TITLE
Urgent: No Webhooks since 04:24:14

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#238]
We're just receiving pings but no Information for reservation changes.

The last message came at 04:24:14  
Normally we receive ~5 messages per minute. 

Is there a problem? Our customers sent us some emails because of this.

**Comment by pgrm** [comment]
@c2ofh, yes, sorry about that. It should be working again, we're currently updating our monitoring infrastructure to notice these issues earlier.

**Comment by c2ofh** [comment]
@pgrm again the same issue. No webhooks since 00:08:59
How could we get it stable? :/

**Comment by pgrm** [comment]
hello @c2ofh we started setting up the monitoring yesterday. It should be available next week to help us figure out what is going on there. The issue seems to be a bit more tricky, as a handful of events were processed correctly. However, yes, all of the events for your clients failed and were re-delivered today around 10am

**Comment by c2ofh** [comment]
Hello @pgrm thank you for the quick response. Only minutes after my post, all webhooks arrived.
The re-delivery is good, so everyone get informed, even a little bit later.

**Comment by c2ofh** [comment]
Hello @pgrm It looks like it stopped again.
