### ISSUE TITLE
Using DateFilter

### ISSUE THREAD

**Issue by pieterb82** [apaleo/api#243]
I want to make use of the dateFilter parameter in the /finance/invoices url. When I try swagger I'm getting back the following error: 

`{
  "messages": [
    "DateFilter: Invalid value provided."
  ]
}`

I have tried the following variables in Swagger:

`
["2019-10-16T08:20:55+01:00"]
["2019-10-16"]
["16-10-2019"]
[2019-10-16]
`
None of these seems to be working, could you please explain the correct format?

**Comment by WinniX** [comment]
Hello @pieterb82

If you want to filter by certain day, in swagger you could just use `eq_2019-10-16`. Instead of `eq` you could use any other operation type (listed next to the field in swagger):
'neq' for not equals
'lt' for less than
'gt' for greater than
'lte' for less than or equals
'gte' for greater than or equals

Please also see the screenshot.
![image](https://user-images.githubusercontent.com/426392/69816012-d9639d80-11f7-11ea-92d4-cb67736083f0.png)

Hope this helps.

Eugene / apaleo Team

**Comment by pieterb82** [comment]
Hi Eugene, 

Did something change to the way we need to use dateFilter? 

I get back this response from the API "DateFilter: The value 'eq_2020-02-02'' is not valid for DateFilter."

**Comment by WinniX** [comment]
Hi @pieterb82,

you are right. From now you need to include a time part as well, like this: `gt_2020-02-10T00:00:00Z`

Eugene / apaleo Team
