### ISSUE TITLE
Reservations are missing

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#247]
## Question

A customer asked why there are some reservations missing in our system. There is a list of reservations. I've checked the logs, but can't find a webhook with it. How can I send you some more information about the case? without posting it public?

**Comment by pgrm** [comment]
hello, @c2ofh please send the IDs to support@apaleo.com include which endpoint is registered for the subscription and if you know, when you were supposed to get those reservations.

Thank xou

**Comment by pgrm** [comment]
thx for the email @c2ofh - I've checked the reservations. They were created before you subscribed for the webhooks. Please understand, that we won't send you a list of past events, once you subscribe, since it might be just too many and we don't know if they are even relevant to you. Instead, you should do an initial sync after you created the webhook subscription. After being the crucial part of the order here, in order to guarantee that you won't miss any updates.

Hope this helps. I'll make sure to include this hint also in the guides.
