### ISSUE TITLE
credit card information

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#26]
## Question

How to get the informationn whether a credit card was deposited or not?
Am I able to update missing credit card details to the guest/reservation?

## Background

If the guest wants to check out, I want to offer the ability to pay the open amount by triggering the payment.

**Comment by andreastubbe** [comment]
**Question 1**
To check if a reservation has a credit card, check if a *payment account* exists on the reservation.

**Question 2**
I assume that the guests will enter his credit card data themselves, on some UI, right? One way to do it, is to
- integrate the adyen payment UI widget (https://docs.adyen.com/developers/checkout/web-sdk). That way neither you nor we ever have to touch CC data, because PCI.
- use the *payer reference* you get back from adyen and call PATCH /booking/v1/reservations/{id}

Does this answer your questions?

**Comment by c2ofh** [comment]
@andreastubbe sorry for my late response to that topic. As you know the priority has changed for some extensions.

Do we need Adyen to let the geust check his credit-card number?
For the first step we want to enable the self check by the guest. to say if the stored credit card is correct.
Maybe to show the number in an anonymisized way **** **** **** 1234

If it's not correct, to let the guest enter his credit card. I'm not really into this topic. :)

I also found no way, when creating the booking, to add the credit card number.
I've filled "Garanty" with "CreditCard"

**Comment by andreastubbe** [comment]
Just *checking* the CC is easier. In the booking and the reservation, you'll find the paymentAccount. This has the "anonymised" version of the credit card, which you can display.

For entering the CC, you need to use the adyen widget. Because security. It takes the raw data, and returns you the fields you need for the apaleo-paymentAccount. Once you have that, just PATCH the reservation. Never did it before, but adyen's documentation is quite good.

**Comment by c2ofh** [comment]
Thank you very much @andreastubbe
