### ISSUE TITLE
Webhook does not react on block creation/change

### ISSUE THREAD

**Issue by remywrevcontrol** [apaleo/api#263]
## Question

I've added the following Webhook for test Hotel LND (XXX are removed data):

```
array(1) {
  [0]=>
  array(8) {
    ["id"]=>
    string(36) "XXX"
    ["topic"]=>
    string(11) "Reservation"
    ["topics"]=>
    array(3) {
      [0]=>
      string(11) "Reservation"
      [1]=>
      string(5) "Folio"
      [2]=>
      string(5) "Block"
    }
    ["endpoint"]=>
    string(42) "XXX"
    ["endpointUrl"]=>
    string(42) "XXX"
    ["created"]=>
    string(27) "2020-01-30T13:02:53.017657Z"
    ["propertyId"]=>
    string(3) "LND"
    ["propertyIds"]=>
    array(1) {
      [0]=>
      string(3) "LND"
    }
  }
}
```

However, when I create a reservation I get a notice, not when I create a block. (I don't know why it says 'topic' and 'topics', because I created the webhook for the ones given under 'topics').

**Comment by randyrod** [comment]
Hey @remywrevcontrol,

Could you please send your `SubscriptionId` to `support@apaleo.com`, with a link to this issue just for tracking purposes. That will help me to track your subscription in our logs.

Randy.

**Comment by randyrod** [comment]
Hey @remywrevcontrol,

I forgot to ask, by any chance do you have the ID of the block that you created, which you did not get the webhook notification for?

**Comment by remywrevcontrol** [comment]
Block ID: GOMSGWFT

**Comment by randyrod** [comment]
Hey @remywrevcontrol,

I quickly checked our logs, using the group id `GOMSGWFT` and block id `LND-OFTUJN` it turns out that the block was created at `2020-01-30 12:58:03 UTC` and the subscription was created at `2020-01-30 13:02:53 UTC`. 

We only guarantee delivery of events that were created at least a minute after the subscription, although you might receive previous events, but usually not more than just a few seconds.

I would also recommend subscribing to the `Group` topic, as it works closely with the `Block` topic. The group events would trigger when anything within a group booking occurs, whereas the Block topic triggers events that only occur within blocks of a group booking.

Here is our guide if you would like to read more about webhooks https://apaleo.dev/guides/start/webhook/

Regarding the fact that you see the `topic` and `topics` results it is just that the `topic` property is deprecated and in the process of being removed, the same case is for `propertyId` and `endpoint`. You can ignore those.

I hope this information is helpful.

Regards,
Randy

**Comment by remywrevcontrol** [comment]
Huh, I first added the webhook, then logged on to the hotel and created the block... So, your timestamps are off...

**Comment by randyrod** [comment]
Hi @remywrevcontrol,

I just went ahead and created a new block  with id `LND-EVIWWL` in the group with id `GOMSGWFT` just to make sure, and after checking our logs, I can see that the webhook was sent and delivered successfully.

Hope the information is helpful.

Randy
