### ISSUE TITLE
Mixed languages in reservation response

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#273]
`Apaleo-Tracking-Id`: 0HLTJMJ8NNPPC:00000260

**Expected behavior:**

We're sending in Headers `Accept-Language: 'de'`. I expect to get all information in 'de' if possible.  
The customer said, that these information are available in german.

**Actual behavior:**

Now in the reponse the cancelation information are in english.
![mPBXsHR2oQ](https://user-images.githubusercontent.com/10913793/74721290-6e929300-5237-11ea-86c3-2371ef963cb7.png)

**Comment by pgrm** [comment]
@c2ofh 

everything works correctly, and you also had all right to be confused, in this case it's the customer who kind of tricked you 😉 

yes, there is a German text for the NONREF cancellation policy, but it's not a translation, it's simply a copy paste of the english text:

![image](https://user-images.githubusercontent.com/713456/75092450-df0f1c00-5577-11ea-9059-c62ded815c3f.png)

Another thing to keep in mind, even if the guest changes the description of the cancellation policy, it will only affect new reservations. We cannot modify existing reservations. So that description won't change anymore, but they should update their translation and afterwards new reservations would be correct.

Hope this clarifies everything.
