### ISSUE TITLE
How do I configure the webhook for subscription?

### ISSUE THREAD

**Issue by dgiebe** [apaleo/api#275]
## Question

Hi Apaleo Team,

I am currently trying to write a program which gets data from your service via your Webhooks. Therefore I got two questions:
**How do I configure the Webhook to send me the all existing reservations to my endpoint once the subscription is done?**
**With which service/interface can I query for the details of data with a given entityId?**

In the following I have got an example program:

```
<?php

require_once('.*/SwaggerClient-php/vendor/autoload.php');
$token = <myTokenStr>;
$config = Swagger\Client\Configuration::getDefaultConfiguration()->setHost('https://webhook.apaleo.com');
$config = Swagger\Client\Configuration::getDefaultConfiguration()->setAccessToken($token);
$apiInstance = new Swagger\Client\Api\HealthCheckApi(new GuzzleHttp\Client(), $config);
$url = "<ourDomain>/testFile.php";
try {
        print_r ($apiInstance->pingerPostWithHttpInfo($url));
        echo "Ping is working"
} catch (Exception $e) {
        echo 'Exception when calling HealthCheckApi->pingerPost: ', $e->getMessage(), PHP_EOL;
}
$apiInstance = new Swagger\Client\Api\SubscriptionsApi(new GuzzleHttp\Client(), $config);
try {
        $model = new \Swagger\Client\Model\CreateSubscriptionRequestModel(["topics" => ["Reservation"], "endpoint_url" => $url]);
        print_r ($apiInstance->subscriptionsPost($model));

Array ( [0] => Swagger\Client\Model\SubscriptionResponseModel Object ( [container:protected] => Array ( [id] => 788c5e88-64f5-47e0-bcfb-c8e841460114 [topic] => Reservation [topics] => Array ( [0] => Reservation ) [endpoint] => <ourDomain>.testFile.php [endpoint_url] => <ourDomain>.testFile.php [created] => DateTime Object ( [date] => 2020-02-19 14:45:40.394221 [timezone_type] => 2 [timezone] => Z ) [property_id] => [property_ids] => ) ) )
*/
} catch (Exception $e) {
        echo 'Exception when calling HealthCheckApi->pingerPost: ', $e->getMessage(), PHP_EOL;
}

?>
```

My endpoint file looks like this:

```
<?php
$data = json_decode(file_get_contents('php://input'), true);
$data = file_get_contents('php://input');
file_put_contents('response.txt', $data, FILE_APPEND | LOCK_EX);
file_put_contents('response.txt', "\n", FILE_APPEND | LOCK_EX);
http_response_code(200);
?>
```

What I receive when I call the test program is the ping data from the Apleo server like:
```
{"id":"234609a4-bb57-4253-a896-fb878145ba7e","topic":"system","type":"healthcheck","accountId":"TDWP","propertyIds":[],"propertyId":"","timestamp":1582123548446}
{"id":"06e2c0e7-c859-4e82-8927-3aba5e87e800","topic":"system","type":"healthcheck","accountId":"TDWP","propertyIds":[],"propertyId":"","timestamp":1582123608460}
{"id":"6a5f3d13-473d-4b30-b056-4d6382315c7f","topic":"system","type":"healthcheck","accountId":"TDWP","propertyIds":[],"propertyId":"","timestamp":1582123667473}
```
Continuously for the last hours.

However I do not get any existing data from our test account. In fact I do get updates in case I create a new reservation such as:

```
{"id":"453ce02e-8975-43c2-ae2f-7811b93b2054","topic":"Reservation","type":"checked-in","accountId":"TDWP","propertyId":"LND","timestamp":1582106429077,"data":{"entityId":"OCZDCDML-1"}}
```

But I am missing the information which is already stored in there. 
Can anybody help me there and point me to what is missing?

In addition I do not know how I can get the full data for this reservation. 
**Do I have to query Apeleo anyhow using this entityId? Which Service do I have to use for that?**

**Comment by pgrm** [comment]
Hello @dgiebe 

> How do I configure the Webhook to send me the all existing reservations to my endpoint once the subscription is done?

you can't webhooks are meant for real time updates only. They don't keep track of old events. So, AFTER you registered the webhook, you should fetch all existing reservations based on the filters, which you care about (or simply all the reservations). - Keep in mind to do it after the registration, as you could miss out on reservations otherwise.

> With which service/interface can I query for the details of data with a given entityId?
> Do I have to query Apeleo anyhow using this entityId? Which Service do I have to use for that?

You can use the services under api.apaleo.com to fetch the additional data. In case of reservations, for instance, you can find the relevant services at https://api.apaleo.com/swagger/index.html?urls.primaryName=Booking%20V1

Hope this clarifies how everything plays together.

**Comment by dgiebe** [comment]
Hi Pgrm,

ok understood, so I will use the linked API to query the already stored reservations.
One question for that:

In order to get all the reservations for a given Hotel I suppose I have to use this API: "/booking/v1/reservations" That is correct, isn't it?
Just trying this in the swagger WebUI (what you linked in your answer) without any filtering I get all reservations for all my three test hotels (Berlin, Munich and London).
Which seems to be correct so far.

When I want to get the reservations for e. g. Berlin (--> "BER") only, I think I need to define a filter which matches this path:

```
"reservations": [
        {
          "id": "TCVQSSUW-1",
            ….
          },
          "arrival": "2020-02-27T17:00:00+01:00",
           ….
           "property": {
            "id": "BER",
            "code": "BER", <!--- This
            "name": "Hotel Berlin",
            "description": "Erkun…."
          },
          "ratePlan": {
          ….
          },
```

So I tried to put this anyhow in to the "property" field in the WebUI, but the filtered result still contained everything.
Could you let me know how I can define a filter for that? In the Webhook we needed to specify a topic for that.

**Comment by WinniX** [comment]
Hello @dgiebe 

Sound weird, that you do see reservations for other properties, rather than just for the one you are filtering by. Could you make sure that your Swagger WebUI filter look like on the screenshot below?
![image](https://user-images.githubusercontent.com/426392/75093611-a2492200-5583-11ea-9e63-7d2a803f1223.png)

Also, you can check the `Curl` query, which you can find below the `[Execute]` button, whether it contains `/reservations?propertyIds=BER` or not.

And lastly, needless to say, that whenever you see a filter key containing `*Id` or `*Ids` (e.g `propertyIds`), it's better to rely on `id` of the entity, not the `code`. Of course, in case of property entity `id` is equal to the `code`, but this can't be applied to other entities and might be changed in the future. 

Hope this helps =)

Eugene / apaleo Team

**Comment by dgiebe** [comment]
Hi Eugene ,

ok I double checked it following your example and it works! Think it was probably a problem in the authorisation and then when it didn't return anything I eventually confused the response value with the example output.

Thanks for your help!
