### ISSUE TITLE
booking/v1/available-unit-groups does not take into account definite block reservations

### ISSUE THREAD

**Issue by remywrevcontrol** [apaleo/api#278]
**Code**
booking/v1/available-unit-groups

**Expected behavior:**
definite block reservations should lower the availability of the specified room types

**Actual behavior:**
block reservations does not lower the availability of the specified room types

**Related Issues:**
maybe an extra query parameter can be used if definite block reservations should be counted or not

**Comment by dario-hd** [comment]
Definite block do reduce availability. As you can see in the screenshot below, having a unit group with a physical count of 3 and having a definite block for 2 units, only 1 unit is available:

![image](https://user-images.githubusercontent.com/14803089/75444400-a4382a00-5963-11ea-9937-9493c5b2e79c.png)

I hope this helps.

**Comment by remywrevcontrol** [comment]
Sorry, problem is that in our system we have not received a cancellation for the blocks yet. We received the last update for one of the cancelled blocks on 2020-01-28 13:15:36.
The question therefore then remains, why did we not receive a block cancellation webhook call?

**Comment by dario-hd** [comment]
Could you please tell us the block id?

**Comment by remywrevcontrol** [comment]
BRU01-SXSYCB

**Comment by dario-hd** [comment]
I cannot find those blocks and it seems there is no trace of them in our logs.

**Comment by remywrevcontrol** [comment]
Both have Group ID: TVBXXZHL. How come then that they are in our system?

**Comment by dario-hd** [comment]
Ok, I found info about the BRU01-VXGXKK block. It was deleted on 28/01/2020 12:18:38PM from our UI, not canceled. About the webhook, that happened too far in the past and we don't have such logs anymore. We started publishing webhooks for blocks only around 20th January so you probably didn't subscribe to the blocks webhooks when those blocks were deleted. Another possible cause could be that you are only reacting to canceled events? Or, we also noticed that you recently deleted a webhook subscription and created a new one a couple of minutes later. In such a case we suggest you using PUT otherwise, you would lose the webhooks between the deletion and the creation of the subscription.

**Comment by remywrevcontrol** [comment]
Hi Daria, thanks for the info. One last question for confirmation: If the block is deleted, do we receive a webhook for that block? And what happens when we request information for that block, do we get a "404 | The Request-URI could not be found." or do we get something else?

**Comment by dario-hd** [comment]
As you can see [here](https://apaleo.dev/guides/start/webhook/configuration) we publish a webhook in case a block is deleted. GETing a block that was deleted results in a 404. Blocks can be physically deleted from our system.
