### ISSUE TITLE
Do user password resets also reset refreshTokens?

### ISSUE THREAD

**Issue by EdwardIII** [apaleo/api#280]
## Question

We're seeing a spike in access issues on `https://identity.apaleo.com/connect/token` with errors like this:

```json
{"error":"User <email> has no access to <chain id>"}
```

One of the users got in touch and told us they'd had a security notification to update their password.

1. Are you having everyone update their passwords, or is there some kind of pattern (e.g. password is > n days old?)

2. Does changing the password invalidate the refreshToken?

Thanks!

**Comment by WinniX** [comment]
Hello @EdwardIII 

The reason for getting the error like `User <email> has no access to <chain id>` is because your user has been deactivated. 

As for security notifications, we do not send any emails like this (regarding password update required or whatever else). If you have received anything from us - please forward the email to support@apaleo.com, so we could investigate.

Eugene / apaleo Team
