### ISSUE TITLE
Cancellations of rooms doesn't work properly

### ISSUE THREAD

**Issue by DFI-HP** [apaleo/api#286]
Cancelling rooms didn't work properly for reservations which lead to us creating more rooms instead of replacing them with the new version.

**Comment by dario-hd** [comment]
Hi, could you please provide us with more details? What exactly didn't work? Did you receive an error? You didn't receive a notification? If you received an error, a tracking id might help us.

**Comment by DFI-HP** [comment]
Our modify of a booking is supposed to cancel some of your rooms and then add new rooms. This however didn't go through, resulting in us only creating more rooms instead of cancelling some, followed by adding new rooms. We didn't receive an error. It appears like the cancelling of rooms is not working properly.

**Comment by dario-hd** [comment]
So you are canceling and re-creating reservations instead of modifying reservations? Even if this would work for confirmed reservations, it's not ideal. We are going to need more details, what do you mean with "this however didn't go through" and "it appears like the cancelling of rooms is not working properly"? Without any further information, we won't be able to help you with this.

**Comment by DFI-HP** [comment]
Yes we are aware of that, but unfortunately there is no other work around for our system. The response code we get is 204. May we discuss the issue further privately?

**Comment by pgrm** [comment]
@DFI-HP 204 means that everything was successful and there is no response - I assume you get this code after canceling the reservation - so it should be canceled correctly

**Comment by DFI-HP** [comment]
Sorry for the late reply.

@pgrm yes I also thought that was the case, but according to our client the cancellation didn't work and no rooms were removed from the reservation. I will try to contact our client to see if this problem still remains. We also certified everything so based on the code it should theoretically work, that's why I am confused of the fact that a 204 response code apparently doesn't work.

**Comment by pgrm** [comment]
@DFI-HP do you have some more details, like the reservation ID and when exactly you tried to cancel the reservation? we can look it up in our logs, if it was within the last 30 days - otherwise if it happens again, it would be easiest for us, if you could provide us with the `apaleo-tracking-id`-header, which you get as part of the response. It'd look similar to `0HLV1AIGAATKH:000001B5` - if you don't have that, the reservation ID together with a rough time period might work as well.

Regards, Peter
