### ISSUE TITLE
Cancellation/noshow fees in reservation (not in folio)

### ISSUE THREAD

**Issue by Beonprice** [apaleo/api#290]
## Desired requirement
Cancellation/noshow fee added to the reservation, without requesting every folio 
## Use cases
Once the complete reservation loading is done through API or webhooks, we would need to get the fees associated to cancelled or noshow reservations. Nowadays, it is needed to do many requests (once per folio) in order to get this information. In order to improve the performance, it would be nice if you could get all cancellation/noshow fees charged to the client directly in the reservation.

**Comment by bennetone** [comment]
Thanks fo reaching out @Beonprice!

I understand for the initial loading of reservations that it is cumbersome to load each folio, but when you are then reacting on the cancellation event from the webhooks it is in most cases 2 calls instead of 1, right? There is so much information attached to a reservation, it would be also a huge overhead for us to always load all folios for the 10 percent of cancelled or no-show reservations.

Just having a summary on the reservation would also not help, because sometimes the cancellation fee might have been moved to another folio. For a revenue management application this might be irrelevant, but for a guest communication app it might be relevant who actually paid the cancellation fee. From experience we learned that you cannot serve all use cases with one API model.

Nevertheless we have thoughts on building a real data extract API, that is read optimized and indexed. There we would allow you to load hundreds of reservations at once and on demand include any additional resources related to each reservation in a denormalized way.

Thanks for the insight, though. We will consider it in our plans for the future.

Kind Regards,
@bennetone

**Comment by ruitguerra** [comment]
Hi Benjamin.
I have heard of APIs using GrapQL to facilitate some integrations, namely
in Hospitality.
Have you heard of it? Would it help for cases like this?
Best regards, Rui

*RUI TEIXEIRA GUERRA*
*CEO - Hotelappz*

*www.hotelappz.com <http://www.hotelappz.com/>*
rui.guerra@hotelappz.com <ruitguerra@hotelappz.com>
+33 6 6155 5460

[image: http://www.hotelappz.fr/] <http://www.hotelappz.fr/>


<https://www.linkedin.com/in/ruiteixeiraguerra/>

Want to Know you Guests better? Find out what Hoteliers think about
Hospitality CRMs
<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>

*HotelAppz interviews 3 seasoned and forward looking Hoteliers*

<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>
[image: HotelAppz interviews 3 seasoned and forward looking Hoteliers]
<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>




Le mer. 25 mars 2020 à 14:41, Benjamin Schmid <notifications@github.com> a
écrit :

**Comment by pgrm** [comment]
Hello @ruitguerra thanks for the suggestion. We're always exploring new possibilities to connect to apaleo and if more partners will request GraphQL we can definitely have a closer look in how it could be applied to apaleo
