### ISSUE TITLE
How to request a refresh token

### ISSUE THREAD

**Issue by arif-voicedev** [apaleo/api#30]
## Question

Hi,
in my scenario I think there's no need to implement the full OAuth2 flow as there'll be just one hotel. I'm using this [instruction](https://apaleo.com/getting-started-with-apaleo-apis/) to request short-lived access tokens by using the id/secret credentials.
Is there an easy way to request a refresh token that doesn't expire, such that keeping the secret on server-side is no longer required? And can that token be limited down to the necessary scopes only?
## Background

AWS

**Comment by andreastubbe** [comment]
The token will be limited to the scopes you need. Right now, we let you access everything - but that's because you're on sandbox. When moving over to production, you'll get new client credentials, limited to the scopes you ask us to include.

I don't think we can issue refresh tokens for the simple access credentials. However, a refresh token that lasts forever should be kept equally secret as your client secret.

**Comment by arif-voicedev** [comment]
Alright. Then we'll work with the simple access tokens while holding the id/secret pair on server-side. 
Thank you very much for your explanation 👍
