### ISSUE TITLE
Question and error in request: PUT /rateplan/v1/rate-plans/{id}/rates

### ISSUE THREAD

**Issue by Beonprice** [apaleo/api#303]
Hello!

we are trying to send a recommendation using your online Swagger executing following request:
PUT -> /rateplan/v1/rate-plans/{id}/rates
![1](https://user-images.githubusercontent.com/62599629/79425359-deb45f80-7fc1-11ea-86b8-f6fc2de78b88.png)

In the body json value we are sending a FROM-TO dates but we are getting the error shown in the above screenshot. 
If we get information (GET request) about that rate plan we obtain:
![2](https://user-images.githubusercontent.com/62599629/79425413-f1c72f80-7fc1-11ea-8d3f-f3e79a61aaa1.png)
Note: We've also tested setting in the PUT request from 17pm until 10am and didn't work as well.

Additionally, on the online PUT request documentation we can read: 
_> All rates specified in the request will be initialized, or overwritten if they already exist._

But below is written:
_> Make sure that the from and to date and time in the rates match the time slice definition of the rate plan. The easiest way to achieve this is calling the GET /rate-plans/{id}/rates for the time range you want to update and then resend the payload with the set prices and restrictions.
You must have this scope: 'rates.manage'._

From our point of view, we would not mind if a rate plan has already configured from-to dates. If the client desires to send the recommendation, your system should accept it although it is not in the date range (the behaviour should be as in the first paragraph (..._initialized or overwritten_...).

Please, could you give us some hint about:
- why the swagger PUT request is not working 
- how it is handled in your system if the client sends a recommendation out of the defined date range

Regards

**Comment by dario-hd** [comment]
Hi,

when sending rates the time is also important. You don't have to figure it out yourself, instead here's what you should do:
* GET rates for the desired time range (e.g. from: 2020-04-29 to: 2020-04-30)
* Manipulate the price and/or restrictions in the response you get
* Send it back with PUT rates

From the screenshots, I can see that you didn't set the time. In this way, the rates don't match and they are not accepted. Try to follow the approach above, when it doesn't work, you can always send us the tracking id you get in the response header so that we can see the incoming request.

**Comment by Beonprice** [comment]
Hi Dario,

thanks for the info! We've already done some adjustments in our development and everything now is everytyhing working as expected. The 'problem' was related with how we were setting the timezone offset on the FROM/TO parameters.

Regards and thanks for the support
