### ISSUE TITLE
When creating non-refundable bookings - why are the charges not posted immediately

### ISSUE THREAD

**Issue by nziehn** [apaleo/api#307]
## Question

When we are creating bookings which go immediately into non-refundable, why are the charges not yet posted? If we cancel such bookings, the balance goes to 0 despite not being paid, yet, and the charge gets deleted.

## Background

If we call `.../{folio-id}/post-charges` the balance & charges are retained properly, but this is only possible for bookings with move-in soon.

**Comment by nfidirko** [comment]
Hello @nziehn,

> why are the charges not yet posted?

because of accounting. When charges are posted, it means that services were provided and we should report VAT for that. VAT % can be different for different services. Cancellation fees, on the other hand, can be subject to a different VAT rate.

So, when a reservation is canceled, all charges are deleted, and a cancellation fee can be posted instead.
They're managed by cancellation policies.

So, for your non-refundable rate plans, you can:
1. make sure that the cancellation fee is configured correctly (100% of the stay).
2. create a cancellation policy for non-refundable rate plans.
3. add the cancellation policy for your non-refundable rate plans.

To learn more about them please refer to the following guides;
- https://apaleo.zendesk.com/hc/en-us/articles/360015655511-Cancellation-and-no-show-fees
- https://apaleo.zendesk.com/hc/en-us/articles/360001719032-Cancellation-Policies

**Comment by nziehn** [comment]
Hi @nfidirko ,

thanks for your support - to my understanding this is exactly the setup that we have in this case.

Account: CPKU, reservation: ASGWHBZZ-1

I would have expected that the above reservation would not be balanced.

**Comment by nfidirko** [comment]
Hi @nziehn,
I've checked that reservation.
Indeed, nothing was posted when a reservation was canceled.
It only makes sense to post a cancellation fee if you would be able to collect it.
Otherwise, you wouldn't even be able to find that person and ask him to pay, right?

To be able to collect and post cancellation fees, you should enable payment automation.
Here is the guide: https://apaleo.zendesk.com/hc/en-us/articles/360000987751-Payment-Automation
The settings you're looking for are located there (Settings -> Payment -> Enable Payment):
![image](https://user-images.githubusercontent.com/44359125/80469819-c8a38900-8949-11ea-98c3-cb2d9531f520.png)

Or, you can also manage those settings via capture policies API:
https://api.apaleo.com/settings/v1/capture-policies
and the setting is called `captureCancellationFee`
