### ISSUE TITLE
OpenID

### ISSUE THREAD

**Issue by v-anton** [apaleo/api#309]
## Question

We're using AWS Cognito for authorization in our service and trying to connect Apaleo as OpenID Connect provider. Currently, we have an issue initializing authorization flow with **openid** scope. Apaleo front-end says **unauthorized client** when I'm adding **openid**
scope to the following link: https://identity.apaleo.com/connect/authorize?response_type=code&scope=offline_access companies.read reports.read logs.read invoices.read folios.read reservations.read availability.read offer-index.read offers.read rateplans.read-corporate rates.read maintenances.read setup.read accounting.read distribution:subscriptions.manage distribution:reservations.manage integration:ui-integrations.manage&client_id=xxx&redirect_uri=xxx&state=YOUR_RANDOM_VALUE

Is it a known behaviour? Because basically openid scope support is listed here: https://identity.apaleo.com/.well-known/openid-configuration

## Background

Request id: 0HLV86B4BVJLG:00000152

**Comment by pgrm** [comment]
@v-anton thanks for all the details you provided, it's a joy to be able to help you this quickly 😸 

If you were logged in, into your account you should see a detailed error message saying

> Requested scope not allowed: openid

This is, because the openid scope wasn't enabled for your client. I'll enable it now and you can try it again in 5 minutes

**Comment by v-anton** [comment]
@pgrm seems like it works perfectly now! Thank you a lot, Peter!
