### ISSUE TITLE
Price missing in ARI response

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#316]
## Question
While trying to retreive ARI updates, we are not receiving prices in the response. Please let us know, what is missing from our end to get the price updates as well within the ARI updates response.

**Comment by bennetone** [comment]
Hey @VasaviBoddeti 

When you do not recveive prices for specific days in the ARI updates it can have multiple reasons. It is all documented in the [channel integration guide](https://apaleo.dev/guides/business-cases/channel-integration/ari-data#prices):

![image](https://user-images.githubusercontent.com/25197867/81058565-f7cc7400-8ece-11ea-92eb-c650589c2125.png)

Check the setup of the respective rate plan and the channel code you are using in the subscription to identify any issues.

Also note that you only receive a full push of data once a day and when you modify your subscription. Otherwise you only receive updates for data that was changed in the meanwhile. If you do not change the prices for specific days, you will not receive any new prices during the day.
