### ISSUE TITLE
Webhook event inconsistency with `propertyId` or `propertyIds` field

### ISSUE THREAD

**Issue by IBestuzhev** [apaleo/api#317]
## Question

We use webhooks subscription. And this morning we noticed that different type of events have different schema. The question is about `propertyId` vs `propertyIds` attribute. Looks like we need to check for both now. Is it possible to get some details, what attributes to use for what event types?

## Background

Events of type `healtcheck` are affected.

So for `reservation.created` nothing changed:

```
{
  "Topic": "Reservation",
  "Type": "created",
  "Id": "xxx",
  "AccountId": "xxx",
  "PropertyId": "xxx",
  "Data": {
    "EntityId": "xxx-1"
  },
  "Timestamp": 1588761533215
}
```

But for `system.healthcheck` the schema is updated

```
{
  "accountId": "xxx", 
  "id": "xxx", 
  "propertyIds": [
    "xxx"
  ], 
  "timestamp": 1588758802502, 
  "topic": "system", 
  "type": "healthcheck"
}
```

**Comment by randyrod** [comment]
Hey @IBestuzhev 

Thanks for reaching out.

We have made it possible to create a subscription for multiple properties, you can read more about it here https://github.com/apaleo/announcements/issues/35. That meant that we have marked the `propertyId` as deprecated and replaced it for `propertyIds`

A good thing to point out is that `Healthchecks` webhooks are nothing more than their name, and should not need any action from your side.

The reason as of why the `healthcheck` event and the`reservation create` event are different is because of the following reasons:

1. Healthcheck events are based on the subscription, so the information you see for the `PropertyIds` is just the properties that this subscription is assigned to.
1. The reservation created event contains `PropertyId` because it only shows the property for which this event happened.

I would also like to recommend subscribing to the https://github.com/apaleo/announcements repository so you get the latest information of the new features or deprecations that we release.

I hope this information is helpful, and if you need further information please let us know.

**Comment by IBestuzhev** [comment]
Thanks for explanation. I saw https://github.com/apaleo/announcements/issues/35, we already use new attributes to subscribe.

I realize that we don't need to process `healtcheck` events, but we use the same parser for all incoming events and that is why we noticed it.

**Comment by randyrod** [comment]
Ok great, then everything should be fine.

I will close this issue, and if you have further questions feel free to reach out.
