### ISSUE TITLE
Also allow "1" for boolean query-parameters

### ISSUE THREAD

**Issue by detcoGbR** [apaleo/api#328]
## I want

Some API-calls have query-parameters of type boolean. Those seem to require using the string-representation "true" or "false" (since all query-parameters are strings).
It would be nice if those parameters would also allow using an 0/1 integer (and thus the string-representation "0"/"1")

## Use cases

We create api-wrappers from the swagger.json-files using swagger-codegen (in this case using "php" as target-language). Wenn swagger-codegen encounters a parameter/field of type "boolean", it uses the native boolean type.
This is the right thing when those are used in the body of requests (and are thus converted to json), however when those are used in query-strings, they are used as "0"/"1", which currently leads to an error.

## Examples
For example getting the main-folio of an reservation, this can be done by GET:
`https://api.apaleo.com/finance/v1/folios?reservationIds=XSFPLWZH-1&onlyMain=true&pageNumber=1&pageSize=100`
When using the generated api-classes as:
`$folioApi->getFolios($reservationIds=["XSFPLWZH-1"], $onlyMain=true)` 
I get an error "OnlyMain: The value '1' is not valid for OnlyMain.", because the generated request is:
`https://api.apaleo.com/finance/v1/folios?reservationIds=XSFPLWZH-1&onlyMain=1&pageNumber=1&pageSize=100`

Currently I use an workaround by disabling strict typing on the generated api and passing those parameters as strings:
`$folioApi->getFolios($reservationIds=["XSFPLWZH-1"], $onlyMain="true")`
But that feels wrong...
(actually the above is not php-syntax, getFolios is a function with _many_ parameters, most of them have a default-value of `null`, but you get the idea. The real php-call looks like:
```
$searchResult = $api->financeFoliosGet(
                null,   // property-ids
                null,   // company-ids
                [$reservationId],
                null,  // booking-ids
                null,  // is_empty
                null,  // checked_out_on_account_receivable
                'true', // exclude_closed // the native, boolean `true` is serialized into the getparams as "1", we need
                // it to be "true" instead (otherwise apaleo rejects it)
                null,  // has_invoices
                null,  // created_from
                null,  // created_to
                'true' // only_main, see above
                // all other parameters after this get their default values...
            );
```
)

**Comment by WinniX** [comment]
Hello @detcoGbR 

Sorry for the delay, by some reason this ticket was lost. 

I see that the API might seem a little bit unfriendly for a PHP-specific features. But if we would accept numbers for boolean variables - then we would have created many questions, like: what shall we do if we get "-1" or "2" for a boolean parameter? As a result, we would need to add validation logic, which slows down the request parsing performance and more importantly will bring some discrepancy and disagreement, because some developers could expect that "2" should be considered as `false` and some as `true`.

I am sure you know about various ways of solving this issue in PHP, e.g `var_export()` or `json_encode()` or custom function.

Here at Apaleo we try to avoid any ambiguity for our users. 

---
Eugene / apaleo Team
