### ISSUE TITLE
Is there a limit of rate plans per unit?

### ISSUE THREAD

**Issue by nziehn** [apaleo/api#332]
## Question

Hi, we're planning to update the number of rate plans that we have per property and I would like to check with you whether there are some kind of limits to the number that Apaleo can handle.

We're currently planning to have 200-500 per property.

## Background

We basically have rate plans for any combination of:
- 2 cancellations policies
- length of stay 1, 2, 3+ nights
- room category
- various voucher codes
- breakfast (+other services) available

this alone would mean about 360 rate plans per property

**Comment by dario-hd** [comment]
Hi,

there's no fixed limit in this regards but honestly, 500 rate plans sound like a lot 😅 

How many unit groups do you have to end up with so many rate plans? Do you need the promo codes on every combination?

**Comment by nziehn** [comment]
So calculation is:
2 (cancellation policies)
x 3 (length of stays 1, 2, 3+)
x 5 (cnt room categories)
x 6 (5 voucher codes + 1 version without)
x 2 (breakfast vs no breakfast)

The way how we communicate the vouchers is basically: you get 10€ off, regardless of what normal price you're booking.

**Comment by dario-hd** [comment]
With such requirements I don't see any alternative at the moment. As I said there's no fixed limit but we always recommend keeping the number of rate plans low. First, because of simplicity on your side - it's going to be hard to maintain so many rate plans. Second, the more the rate plans the more the time needed to get an offer. If you are planning to create derived rate plans for all these combinations, keep in mind that there is a limit in the hierarchy: beyond the root rate plan you can create only 3 levels of derivation. For example:

R0 (Root rate plan)
└ R1
    └ R2
       └ R3

**Comment by nziehn** [comment]
Thanks!
