### ISSUE TITLE
Inconsistency with channelCode and channelCodes parameter naming

### ISSUE THREAD

**Issue by lukeclifton** [apaleo/api#34]
Throughout the API, for the channel code parameter, both `channelCode` and `channelCodes` are used. 

https://api.apaleo.com/swagger/#!/Booking/BookingBookingsGet
https://api.apaleo.com/swagger/#!/Reservation/BookingReservationsGet
Both these endpoints use `channelCode` but allow an array of strings to be passed.

https://api.apaleo.com/swagger/#!/RatePlan/RateplanRate_plansGet
This endpoint uses `channelCodes`.

This inconsistency can contribute to bugs as we have identified with the availability calendar feature for UP IBE. We were passing in `channelCode` when it should have been `channelCodes`. This lead to  the parameter being ignored and the api passing back all rate plans without us realising until now.

**Comment by bennetone** [comment]
Hey @lukeclifton 

Thanks for reporting this inconsistency. It is hard to clean this up without introducing a new API version as a lot of API clients are using the endpoints that have to be fixed:
https://api.apaleo.com/swagger/#!/Booking/BookingBookingsGet
https://api.apaleo.com/swagger/#!/Reservation/BookingReservationsGet

We will keep an eye on that and decide if it should be fixed in v1 or we gonna wait for v2.
