### ISSUE TITLE
Booking webhook subscription is never called (change booking note, create new booking, ...)

### ISSUE THREAD

**Issue by simone-montemezzani-3AP** [apaleo/api#382]
Booking ID: `LUIZVQBO`
`Booking` webhook subscription ID: `9310a3df-3913-4617-a564-b05a4fe392a2`
```
[
  {
    "id": "9310a3df-3913-4617-a564-b05a4fe392a2",
    "topic": "Reservation",
    "topics": [
      "Reservation",
      "Booking",
      "Folio",
      "Invoice"
    ],
    "endpoint": "https://xxx.ngrok.io/webhook/apaleo/callback/BER",
    "endpointUrl": "https://xxxx.ngrok.io/webhook/apaleo/callback/BER",
    "created": "2020-08-11T10:07:23.012895Z",
    "propertyId": "BER",
    "propertyIds": [
      "BER"
    ]
  }
]
```

**Code**
* subscribe to `Booking` topic
* Go to https://app.apaleo.com/BER/bookings/LUIZVQBO/reservations?status=Confirmed&status=InHouse
* add a Note to the Booking

**Expected behavior:**
Booking webhook call received

**Actual behavior:**
Booking webhook call is not received

**Related Issues:** 
Same behaviour when creating a new Booking (I only receive the webhook for the created Reservation/Folio/..., never for `Booking`)

**Note**
Not related to `ngrok` (same behaviour on "real environment", `Reservation` webhook received without problem)

**Comment by WinniX** [comment]
Hello @simone-montemezzani-3AP 

Thank you for the details! 
The reason why you don't receive `Booking` events is that the subscription should not have `propertyIds` filter set. The thing is that `Booking` events are cross-property, meaning that they can only be received if you subscribe to the account-level events.
Please have a look at the docs here: https://apaleo.dev/guides/start/webhook/configuration

So, I would recommend you to create 2 subscriptions. First one for property-level events, like Reservation/Folio/Invoice. And the second is for account-level (for Booking topic specifically).

Also we suggest not to use `propertyId` parameter, when you create a new subscription, since this parameter is deprecated and will be removed soon. https://github.com/apaleo/announcements/issues/35

Hope this helps.

---
Eugene / apaleo Team

**Comment by simone-montemezzani-3AP** [comment]
Thanks @WinniX for the quick reply. 

Wow, you're absolutely right, it works perfectly as you suggested, thanks!

I had seen the https://apaleo.dev/guides/start/webhook/configuration documentation a few weeks ago, when the `Booking` topic was not mentioned at all (if my memory serves me right).
Question: is that page up to date? 
* `canceled` type within `Reservation` topic seems to be missing (we have received webhooks with this combination)
* `cance**ll**ed` with two `l` for `Block` but `cance**l**ed` for `Invoice`

Thanks again!

**Comment by WinniX** [comment]
Hey @simone-montemezzani-3AP 

I am happy it works for you. Booking events were introduced a few weeks ago.

Regarding `Reservation` canceled, thank you for spotting this one. We will update the docs.
And speaking of `cancelled` and `canceled`, you are also right, this was done unintentionally. I hope in the future we will bring them to one form.

We always try to keep our guides up to date, but sometimes we may loose some of the updates.

--
Eugene
