### ISSUE TITLE
Booking Channels - CM

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#395]
While we update the Rateplans, we are supposed to receive updates for only those Rateplans for which the Booking Channel is 'Channel Manager'. If this is right, then why are we receiving the updates as "Closed":true for other Rateplans as well for which the Booking Channel is NOT selected as 'Channel Manager'. Please advise.

**Comment by WinniX** [comment]
Hello @VasaviBoddeti 

The reason why are you getting `"Closed": true` for this rate plan is that you have updated the rate plan and removed `Channel Manager` from the list of Booking Channels. 
The logic here is the following, once you've created a subscription in Distribution for a rate plan and specified `channelCode` parameter, you will get the rate plan updates, which relates to this channel code. 
It means, even after you update the rate plan and remove the channel code that your subscription has, you will anyway receive a `"Closed": true` update, because this rate plan is kinda "closed" or deactivated for this channel code.

In case you want to stop receiving any updates for a rate plan - just delete the subscription in Distribution.

I hope this helps.

----
Eugene / apaleo Team

**Comment by VasaviBoddeti** [comment]
Dear Eugene,

Thank you very much for the clarification.

Yes, this helped us understand better. 

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com
