### ISSUE TITLE
Too slow notifications from Apaleo

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#397]
The updates from Apaleo are received too slowly. We are worried about overbookings, if the updates are received with long time lapses. Please advise on how can this be improved further.

**Comment by VasaviBoddeti** [comment]
Dar Team,

Please consider this as a reminder. I haven;t received any reply for this query.

Thank You,
Vasavi

**Comment by dario-hd** [comment]
Hi, what kind of updates are you talking about? Distribution or webhooks?

**Comment by VasaviBoddeti** [comment]
Kindly consider this as a gentle reminder.

**Comment by dario-hd** [comment]
Hi, sorry for the delay. I assume you are using the distribution API. The interval for the delta upload is set to 5 min for all our clients. The chance of overbooking cannot be avoided completely because of the syncing mechanism and we find 5 min to be a good compromise. In case of overbooking, depending on your implementation, we accept the reservations but we add some warnings to it so that the hotel can decide what to do with it.

**Comment by dario-hd** [comment]
When you create bookings, we accept them regardless of availability and restrictions. If there is no availability or some restrictions are violated at the time of the creation of the booking, we accept it anyway and we add a "validation message" to the reservation itself. You don't need to do anything in this regard, the hotel can then decide what to do with such bookings (cancel them, move them to another property, etc).

**Comment by VasaviBoddeti** [comment]
Dear Dario,

Thank you very much for the calrification.

Have a great day.

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com
