### ISSUE TITLE
Create Reservation: Core API or Distribution API

### ISSUE THREAD

**Issue by Rivi-IT** [apaleo/api#401]
## Question

I want to create bookings/reservation from our web-site.
When I connected the custom hotel app in apaleo, i activated "Core (27/27)" and "Distribution".
Now i tried to create a booking by Core API: not allowed.
Then I tried by  Distribution API: HTTP Error 422, Provided value is invalid 

The other Question is: when i have more than one property, how can i set the property for reservation ?

**Comment by bennetone** [comment]
Dear @Rivi-IT,

the distribution API is for integrations with Channelmanger and OTA. When you build an IBE you should use the Core API. Please refer to our documentation here: https://apaleo.dev/guides/business-cases/ibe/

Which scopes you need to add to your client and ask for when you create your access token is documented per each API. To create a booking it is reservations.create or reservations.manage.

![Screenshot_20200830-120157](https://user-images.githubusercontent.com/25197867/91656427-eed46380-eab8-11ea-8a48-2bc5c24cf3d5.png)

If you get a 403, then your API client either does not have the proper scopes configured or you forgot to ask for the scopes when creating the access token.

For your last question: A rate plan is clearly linked to a property, so by just letting us know the rate plan id for a reservation we also know for which property the reservation should be created for. You can not mix rate plans from different properties in one reservation, but you can create a booking with reservations from different properties.

**Comment by Rivi-IT** [comment]
Hi Benettone,

scope are (Core Api 27/27 activated): 
- reservations.manage / read / force-manage (description says: modify, checkin, checkout, cancel. What's about create ?)
- setup.manage / read. here description says: including creating, modifying and deleting units, unit groups, rate plans and properties

Property: When I get the rate plans, i see the hotel id as prefix, but you don't see this when creating items in apaleo. You must know that the hotel id is implicit used when calling the api. This is awful at units= they have an own ID, not derived from Unit Code.

I tried t ocreate a modified booking at swagger: 
- activated admin grant, logged with my admin account
- entered Idempotency-Key, modified booking data
- can't execute 
=> trying to create a Group works, but couldn't create a block

Note: I'm not an php expert, and also starting with apaleo API.

**Comment by bennetone** [comment]
Hi @Rivi-IT 

I think it is best if you write an email to support@apaleo.com and we can see if a short websession can help to give you a better understanding of the concepts..

When you run a call from swagger and authorize the swagger UI with the admin scope, then it is irrelevant which scopes you configured for the `FIM-Test IBE` API client. I checked the logs and you failed to add a reservation to an existing booking, because you missed out on specifying a mandatory property in the request body. You received a response with status code 422 and the following message:
```
{
	"messages": ["Reservations[0].ChannelCode: The ChannelCode field is required."]
}
```

Then you tried it again with a modified request body and received a response with 404, which means the specified resource with the given id does not exist. This is because you called an API that adds one or multiple reservations to an existing booking and you specified the booking id `XPGMSXGF`. In your account no booking with this id exists.

This is very clear from the documentation of the API endpoint:
![image](https://user-images.githubusercontent.com/25197867/91668629-5963be80-eb0e-11ea-8100-4dd6a4660287.png)

If you want to create a new booking, then you should use the following API:

**POST** /booking​/v1​/bookings
_Creates a booking for one or more reservations_

![image](https://user-images.githubusercontent.com/25197867/91668648-8b752080-eb0e-11ea-9286-d2d753c486cf.png)

Regarding the ids of resources like units, unit groups and rate plans. Ids are just ids, they could also be cryptic UIDs. We decided to have ids in a human reaadable format, so it is easier to deal with them and read request and response payloads.

Ids are generated by apaleo when you create a new resource like e.g. a unit group. Here you only need to specify in which property the unit group should be created like in the example on the swagger docs you specify the unit group should be ceated for the property Munich with the id `MUC`.
**POST** ​/inventory​/v1​/unit-groups
```
{
  "code": "DBL",
  "propertyId": "MUC",
  "name": {
    "en": "Double Room",
    "de": "Doppelzimmer"
  },
  "description": {
    "en": "This is a nice room with as kingsize bed and flat screen",
    "de": "Dies ist ein schönes Zimmer mit Kingsize-Bett und Flachbildschirm"
  },
  "maxPersons": 4,
  "rank": 1,
  "type": "BedRoom"
}
```

In the response you will receive the id of the newly created unit group in the response body and in the location header you will get the full URL to load the newly created resource. This is a very well known standard for REST APIs.

When you need to understand for which property a resource like a unit, unit group or rate plan was created for, then you do not need to or even should not parse and try to understand the resource id. Each resource will show you the property id in the reponse body as an attribute.

In general I do not understand how creating units, unit groups or rate plans is related with the implementation of a booking engine. I again would like to point you to our [guide on best practices on implementing an IBE](https://apaleo.dev/guides/business-cases/ibe/).

Have you also considered to look for an existing IBE on our [apaleo store](https://store.apaleo.com/group/distribution-ibe/)? Here you can find existing IBEs that you can easily connect to your account and you can put them live on your website in minutes.

**Comment by Rivi-IT** [comment]
Hi bennetone,

The start with apaleo Api programming was a little bumpy, now we got it.
I found some information misleading, here some examples:
-	reservations.code : not useable for channelCode “Ibe”, this can you find out only by trial and error
-	reservations.TimeSlices: each day must have an timeSlice / ratePlan entry
-	when using api, you need to know that a property is inherit defined at internal id’s (ratePlan)

thanks a lot for assistance.
Rolf
