### ISSUE TITLE
Maximum number of days for ARI updates

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#410]
As and when we do the mapping of Apaleo rates with our rates in our interface, we receive full ARI sync from Apaleo. Here in this full sync, we would like to know, whether the calendar for all the Rateplans will be open and bookable immediately or only when each day is updated with Availability or price or restrictions ? Please advise.

**Comment by WinniX** [comment]
Hello @VasaviBoddeti 

Not sure if I get your question right, but here is some information you may find useful. 
Since you are using Distribution API and `/trigger-full-sync` endpoint, you probably know that this endpoint is supposed to be used only once, when you initialize your local database. After that you need to create a subscription using `POST /v1/subscriptions` endpoint, where you specify an `endpointUrl` to receive only updates.

And about rate plans calendar, in order to make a rate plan bookable you need to set `bookingPeriods` and set rates. 

If my comment doesn't completely answer your questions, please give us more details on which API endpoints you are using and what you are trying to achieve at each step? 

--
Eugene / apaleo Team

**Comment by VasaviBoddeti** [comment]
Dear Eugene,

Thank you very much for the explanation.

As you said, I agree with your statement "Since you are using Distribution API and /trigger-full-sync endpoint, you probably know that this endpoint is supposed to be used only once, when you initialize your local database. After that you need to create a subscription using POST /v1/subscriptions endpoint, where you specify an endpointUrl to receive only updates."

So, while we initialize our database for say upto one year i.e. 365 days, we must also provide some values for Availability and Prices for each of the day that is initialized. But as we may not receive availability and price for all these days from Apaleo as soon as we subscribe, we had to maintain some default values. Is there any alternative for this from Apaleo to fill the availability and prices for all the days as subscribed in the first place itself ?

**Comment by WinniX** [comment]
Hello @VasaviBoddeti 

Could you clarify what's for do you need to have default values? Once you create a subscription - you will be up to date with availability and prices.
