### ISSUE TITLE
iDEAL (and other, non-card payment methods) on Apaleo + Adyen

### ISSUE THREAD

**Issue by EdwardIII** [apaleo/api#416]
## Question

Hey, we talked previously about using non-card payment methods like iDEAL but had to hold off as there were certain aspects that weren't ready at the Apaleo end.

What's the status on this now? Can we just enable iDEAL on Adyen, and it will work the same as cards for the hotelier? Or is the story more complex?

## Background

We want customers on our IBE to be able to use iDEAL and other non-card payment methods.

**Comment by bennetone** [comment]
Hi @EdwardIII,

this is currently been worked on. We already support alternative payment methods on payment links and actually only have to adjust the `POST ​/booking​/v1​/bookings` API to allow you to send in the transaction reference independent from the payment account. Stay tuned, there will be an announcement soon!

Cheers,
@bennetone

**Comment by EdwardIII** [comment]
Hey team apaleo, sorry if I've somehow missed the announcement, is there an update on this?

**Comment by bennetone** [comment]
Hi @EdwardIII 

unfortunately there was no annoucement for this yet. Due to new priorities we had to stop working on this topic and will most probably not be able to take it on again before the beginning of 2021.

**Comment by veikkolaine** [comment]
Hey!

Just did a research for our guests (n=356) and the most preferred method of payment for Finns would be online banking with 41 % share of respondents saying this as their preferred method of payment. 9 % would prefer mobile payments via MobilePay. 

All Finnish hoteliers and other logding providers eagerly looking for this upgrade in order to boost checkout --> booking completion conversion and direct bookings in general.

All the best from up North!
Cheers,
Markus and Hiisi Homies

**Comment by mlaros** [comment]
Hi!

Local payment methods (such as iDeal, Bancontact and Sofort) make up over 45% of our payments. 
We are currently using the UP booking engine, which is awesome in terms of conversion, but we see that drop-off on payment is much higher than normal compared to other booking engines that do support these payment methods.

We would really really like to this see added.

**Comment by ozonni** [comment]
Alternative payment methods support is in our roadmap. [Stay tuned](https://github.com/apaleo/announcements), there will be an announcement once it get's released!
