### ISSUE TITLE
Folios Expand for paymentAccount

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#418]
## I want

The possibility to expand the folio by the paymentAccount of the reservation

## Use cases

If I want to check if it is possible for a guest to pay a particular folio, that would be useful information.

## Examples

When there is a virtual creditcard or a company I'm able to find out if the guest can pay this folio or not.

## What I do

I want to collect the payment for one or more folios in a reservation.
Now I need a second request to get information about the paymentAccount within the reservation.

**Comment by bennetone** [comment]
Hey @c2ofh

you are absolutely right, we should provide apps a clear way to distinguish who is responsible for which charges on a reservation folio. The one that has to pay a reservation folio is the debitor of that folio. You can already now distinguish if it is a person or a company covers for the folio and in case it is a company you can see if the company has an AR account with the hotel and the folio can be checked out with an open balance.

We have on our roadmap to further build this out, so that a digital guest journey app can clearly understand for which folio it has to ask the guest to pay for and which folios are already guaranteed for by a company or travel company.

Thanks for your input!
