### ISSUE TITLE
Update of booker data changes via webhook

### ISSUE THREAD

**Issue by ruitguerra** [apaleo/api#430]
## I want: 
To be able to get updates (via webhook like for Guest data, Reservation/Booking data, etc) of modifications in Booker data, for example booker name, email, etc.

## Use cases

Get updates of the Booker data so that these can be synchronised to the the HotelAppz CRM 
This is particularly important because Hotel clients sometimes want to send transactional or other messages to Bookers, in addition to guests. 

## Examples

When any booker data is changed in Apaleo, HotelAppz gets an on the fly notification via webhook, and pulls the updated data from Apaleo. 

In June, we got the following answer from you:
"Hi @nuno-sousaHZ
currently we do not send any web-hook event when something on the booking including the booker data is modified. We do have this in our backlog to also add booking events."

However when I look at Apaleo webhook events you say that you process the following events: 
"booking created/changed/deleted."
See here: https://apaleo.dev/guides/start/webhook/configuration

Could you confirm when you will send updates of booker data changes ? Which data changes trigger the updates? Is this documented somewhere? 

## What I do

Today it is not possible to do this as we would have to poll all the Bookings/Reservations. 

Thanks,
Rui

**Comment by WinniX** [comment]
Hello @ruitguerra,

there are 2 endpoints at the moment which trigger the booking events:
1. PATCH `/booking/v1/reservations/{id}`
2. PATCH `/booking/v1/groups/{id}`

The first one allows you to update the following properties: `booker`, `paymentAccount`, `comment` and `bookerComment`.
The second, in addition to the first one allows to update `propertyIds`. More details in [Swagger](https://api.apaleo.com/swagger/index.html?urls.primaryName=Booking%20V1).

When you subscribe to the Booking topic, make sure you don't specify any `propertyIds`. Otherwise, you will not get any updates.

Hope this helps.

--
Eugene / apaleo Team

**Comment by nuno-sousaHZ** [comment]
Hi @WinniX ,

Perhaps we didn't understand correctly, but following your explanation, we would have to call these endpoints to update the booker on apaleo's side, and that's not exactly what we need.

What we need is to receive an on the fly notification everytime the booker's information is changed. Like the existing notification for the guests which triggers a 'changed' event.

Let me know if you need more information about this.

Thank you.

Best regards,

Nuno Sousa
