### ISSUE TITLE
Delete oder Modify Services (Extras) on a booking

### ISSUE THREAD

**Issue by moseratgit** [apaleo/api#434]
## Question

Is there a way to modify or delete extras which were added via /booking/v1/reservation-actions/{id}/book-service to a booking?

## Background

customice creates bookings for meetings, everything configured with a meeting is stored as a service on a booking. It would be nice if we could change these somehow, e.g. service for a setup is booked "boarding" and has to be changed to "classroom" - this would mean to delete service "boarding" from the extras and add service "classroom"

**Comment by dario-hd** [comment]
Hi,

in order to modify a booked service you can use the same endpoint you used for booking it, just provide the final state of the service:

![image](https://user-images.githubusercontent.com/14803089/100988504-191e3d00-3550-11eb-82b3-41b5316e63a5.png)

For deleting a service, use the following endpoint:

![image](https://user-images.githubusercontent.com/14803089/100988610-3226ee00-3550-11eb-8405-fe4543dc330a.png)
