### ISSUE TITLE
Bad Request, user has not access

### ISSUE THREAD

**Issue by ojota84** [apaleo/api#437]
## Question

Special user can not access the Apaleo API. There is a user that can log in to the apaleo dashboard.
He goes to the following link
https://app.apaleo.com/{id}/apps/DIALOCK-CONNECT-PROPERTYSETTINGS

While loading the new iframe, we try to get the access_token from the refresh token 
but it didn't work.

Only for this user. All other accounts works.

## Background

 400 Bad Request: [{"error":"User g*******.de has no access to Q**B"}]

**Comment by nfidirko** [comment]
Hi @ojota84,
Could you please provide more details, so that we can check that user?
**Do not post any sensitive information here.**
Instead, you can create a support ticket.
Log into apaleo, click the "?" icon in the upper right corner and submit a ticket there with all the information (which account and user are experiencing issues).


In the meanwhile, here are some ideas you can try out:
- Does the user has access to that account/property? If not, you should add it.
- Does the user has enough permissions for that? If not, you should add them.
- How many roles and properties does the user have? there is a known issue when a user has too many properties/roles which corrupts the auth token.
