### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Aminetb2a** [apaleo/api#461]
I am trying to set up an integration using "https://integration.apaleo.com/integration/v1/ui-integrations/DashboardPropertyContext" to create my UI integration, giving the required payload as follow:
{
    "code": "E102AEC649E27EBFF5C7B9E45196B849DECBF02D4033A74603CD26534DD7D643",
    "label": "Otello Integration",
    "iconSource": "https://hotech.systems/assets/img/hotech-logo.svg",
    "sourceUrl": "https://hotech.systems/",
    "sourceType": "Public",
    "labelTranslations": {
        "de": "Meine Integration",
        "es": "Mi Integración"
    }
}

but I'm getting a 403 Forbidden response.

What could be the reason?

**Comment by randyrod** [comment]
Hi @Aminetb2a,

Thanks for reaching out.

In the logs I can see that you are following the wrong flow to request a new access token. Since you are using the apaleo connect client you need to follow the authorization grant flow instead described here https://apaleo.dev/guides/start/oauth-connection/auth-code-grant.

Regards,
Randy - apaleo Team
