### ISSUE TITLE
Service type explanation needed

### ISSUE THREAD

**Issue by jeanatpi** [apaleo/api#67]
## Question

Dear Apaleo Team,

Got a question on service types. We can have 3 types : 'FoodAndBeverages', 'Accomodation' and 'Other'.

For what kind of services 'Accomodation' is used for and do we need to add it to the baseAmount price in case we encounter one?

Best regards

Jean

**Comment by ozonni** [comment]
It defines to which account the revenue should go. You can define it for rate plan, service or when you post a charge. It has nothing to do with the `baseAmount` .

**Comment by jeanatpi** [comment]
Hi ozonni,

Thanks for your quick answer.

Maybe my question was not very clear.
I need to calculate revenue for a reservation with 4 type : totalRevenue, roomRevenue, foodRevenue and otherRevenue.

To do so I use : 
- roomRevenue = timeSlice.baseAmount.netAmount
- foodRevenue = SUM(service.amount.netAmount) for each included services of type 'FoodAndBeverages'
- otherRevenue = SUM(service.amount.netAmount) for each included services of type 'Other'
- totalRevenue = roomRevenue + foodRevenue + otherRevenue

So my point is more how should I handle services of type 'Accomodation' when encountered?

**Comment by bennetone** [comment]
Hey @jeanatpi 

this rule to put the revenues into the proper buckets works out in general, but there is one additional thing you need to consider. A reservation is done for one unit and in apaleo units can be used for other things than just rooms. Some hotels manage their parking lots as units and define rate plans for them which are configured to use `Other` as service type. I would recommend you use the service type defined on the rate plan booked per time slice instead of assuming it will always be `Accomodation`.
