### ISSUE TITLE
Subledger, transactions and service date

### ISSUE THREAD

**Issue by jeanatpi** [apaleo/api#68]
## Question

Hi,

I'm using Subledger API /finance/v1/accounts/export to fetch transactions and use it to calculate revenues for a date and a reservationId.

My issue is that date field is the date of the booking and not the service date.

Would it be possible for you to add easily the service date to the response?

If not what to you suggest to achieve my goal?
We think about using folios API but the issue is that charges are not included in /finance/v1/folios method. We would need to call /finance/v1/folios/{id} for each results. 
But if you can add a "expand=charges" parameters in /finance/v1/folios that's maybe a solution.

Have a nice day!

Jean

## Background

My goal is to get reservations from past and future.
Then for past, get the real payments done to calculate all revenues (Food, Accomodation and Other).

**Comment by pgrm** [comment]
hello @jeanatpi - the date field on the transaction is the business date of the transaction. If the transaction is from a reservation account to a revenue account, this will be the same as the service date. The only problem you'll face is when charges were moved onto the reservation at a later time. However, this is problematic anyhow as you end up with one of 2 possibly wrong results:

1. You want to take the original service date - which you'd get from the charge on the folio, even if the charge was moved. But in that case it might be that a move of charges in the next month changes revenue statistics in a previous month, which definitely might look weird to the user.
2. You would accept the issue with moved charges, but in that case you don't report the revenue on the correct date.

It seems to me you are fine with potentially creating changed revenue reports for the past, depending on actions in the present, in which case something like expand charges on folio would be probably the best option for you. We are already thinking about it for quite a while, the problem is currently to guarantee a reasonable performance for such an API call, that's why it doesn't exist yet.

Would it be fine to have something like `/finance/v1/folios?reservationIds=RESERVATION-1&expand=charges` or would you want to be able to do it for all folios, without a restriction on reservation id?

I'll bring it up with the team later today and we'll get back to you.

-----

Btw, just a hint:

>  Then for past, get the real payments done to calculate all revenues (Food, Accomodation and Other).

To the best of my knowledge, revenue doesn't depend on payments.

**Comment by jeanatpi** [comment]
Hi @pgrm,

Many thanks for your answer.
For our analytics point of view it's ok for us to report revenue on the "wrong" date.

For now, without modification in API methods we will do the following : 

- call /finance/v1/accounts/export API to get transactions between from and to date.
- foreach receipt.number, call /finance/v1/folios/{id}
- calculate the revenues and update the reservation.

That's not ideal in terms of API call numbers but it will gives us correct results.


For later we have many possibilities : 

1. Add service date in /finance/v1/accounts/export. With this we will be able to update reservations correctly.
2. Modify /finance/v1/folios to add expand=charges to  + from/to filters based on business date (not service date.

**Comment by andreastubbe** [comment]
Jean, we do have the service date in the raw transaction data you are getting. It's the `date` field. Just because you move a charge to a different reservation does not mean that the date when the service was delivered changed.

Additionally, if this is not the date you are looking for, you can use the timestamp instead. This is the date when the move-transaction was recorded in the accounting-transaction-logs.

Andrea

**Comment by jeanatpi** [comment]
@andreastubbe ,

Ok, I certainly missed something.

What you mean is that if I call the API with let say from=2019-01-01 & to=2019-01-20 I will get transactions with "timestamp" between those 2 but also transactions with "date" between those 2 but with a timestamp > 2019-01-20?

**Comment by andreastubbe** [comment]
Yes. If you filter by "service date" / "business date", you get all transactions with those dates. The timestamp can be anything.

**Comment by jeanatpi** [comment]
@andreastubbe 

Thanks. If fact we were confused by a special case.

I can confirm that calling /finance/v1/exports method is fine for now and allows us to get the right results.
