### ISSUE TITLE
unauthorized client calling connect/authorize

### ISSUE THREAD

**Issue by MSRobert** [apaleo/api#74]
## Question
I am in the beginning of the integration and am trying to open the following url in my web browser:

https://identity.apaleo.com/connect/authorize?response_type=code&scope=properties.read&client_id=VASHospitalityManager&redirect_uri=https://vasintelligentsolutions.azurewebsites.net&state=YOUR_RANDOM_VALUE

I expected to get the consent screen but got an error message:

_Something went wrong
Sorry! We could not process your request.
unauthorized_client
Request Id: 0HLKG1A4HRQIT:0000090D_

## Background

I have received the client id and secret of a connect-client for the apaleo api and started with the how to guide on this url https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0

**Comment by ozonni** [comment]
@MSRobert try this url `https://identity.apaleo.com/connect/authorize?response_type=code&scope=properties.read&client_id=VASHospitalityManager&redirect_uri=https://vasintelligentsolutions.azurewebsites.net/&state=YOUR_RANDOM_VALUE`

the only difference is `/` in the end of `redirect_uri` because that's the url we have configured and it has to be 100% the same.

**Comment by MSRobert** [comment]
thank you, it works now!
