### ISSUE TITLE
what is folio id

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#76]
Hi, 
I am using the 'finance/v1/folios' api call to fetch the folio data. 
I am not able to understand the relation of folio_id with. because some folio_id is matching with property_id. 
for example folio ids matching with property_id : AUGSBURG,ESSEN,MONTABAUR, etc. and some not like MOHHMEOF-1-1,CNWBDDMA-1-1 etc. 

Also I want to extract the 'charges' and 'payment' info. Do I need to make separate request for each folio_id?

**Comment by pgrm** [comment]
@patrickHermannLimeHouse 

> I am not able to understand the relation of folio_id with.

relation of foliod_id with what?

The fact that the folio ID looks like some other ID you might recognize is purely coincidental and might change in the future, so please don't rely on it.

Which folios are you looking for? Do you want property folios or reservation folios?

> Also I want to extract the 'charges' and 'payment' info. Do I need to make separate request for each folio_id?

Yes, unfortunately that is the only way to do this at the moment

**Comment by patrickHermannLimeHouse** [comment]
relation of folio_id means is it related with reservation data.

**Comment by pgrm** [comment]
as I said @patrickHermannLimeHouse there is no relation between Entity IDs you can or should rely upon.

Every reservation folio has the property `reservation`, where you can find the related reservation id. You can also search for folios by `reservationIds`. There is no other relation you should try to deduce out of it, because we don't guarantee it and it might change in the future, at which point your code would break. Instead please rely on the additional properties and filters we offer you.
