### ISSUE TITLE
Functionality Reservations API, dateFilter

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#82]
## Question

Hey Guys,

How does the "dateFilter" work in the API "GET /booking/v1/reservations"?

I am especially interested in the option "stay".

Thanks for helping,

Patrick

## Background

I am working on a report which summarizes data about the reservations of all our properties in a specific time.

Sofar i am pulling the data from the Reservations API with "booking/v1/reservations?expand=booker,unit,property,unitGroup,ratePlan". This returns all reservations which are in the system.

Now i am searching for a way how to shorten the list on the actual time period which is interesting for me.

I am trying out the dateFilter in the swagger with authorized access but i always get a Response Code 400. Example: https://api.apaleo.com/booking/v1/reservations?dateFilter=Stay&from=2019-01-01&to=2019-01-31&pageNumber=1&pageSize=100

**Comment by dario-hd** [comment]
I @patrickHermannLimeHouse you are getting a 400 because you should provide also the time, something like:

https://api.apaleo.com/booking/v1/reservations?dateFilter=Stay&from=2019-01-01T00:00:00+01:00&to=2019-01-31T00:00:00+01:00&pageNumber=1&pageSize=100

By using the `Stay` option, you will get all reservations where the arrival/departure range overlaps with the specified range.

**Comment by patrickHermannLimeHouse** [comment]
Got it, thanks. :)
