### ISSUE TITLE
Automatic reservations, add past reservations

### ISSUE THREAD

**Issue by VasilGutev** [apaleo/api#84]
## Question

Could you please continue to add automatically reservations to all of the hotels each month. 
Also is there any way you can add reservations created in February(before today) because I can not do it through the UI and we would like to see comparison between January and February.

## Background

Account name: VAS Value Added Services GmbH

**Comment by andreastubbe** [comment]
Sorry for the late reply - it is not possible to add reservations in the past because that wouldn't make a whole lot of sense in real life.
We do not have the possibility to constantly feed new data into existing hotels. The testing data is mainly there to get the initial implementation done, and usually the initial batch is enough. But if ping us when your hotel gets too empty and you need more, we'll tell our data-bot to create some :)
