### ISSUE TITLE
Extend reservation with room_number

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#9]
## I want

When we pull the reservations via the endpoint `booking/v1/reservations?propertyIds=:property_id`
We recieve all data that we need, but the room data is just the `unit_id`. Is it possible to extend the information with the room number?

## Use cases

We pull all reservations each 5 minutes to get updates. Without this information we have to call the api twice, just to get a room number for this reservation.
The Hotel can not work with a `unit_id`. It's just for apaleo internal use.

## Examples

When a guest is ording a service or making a wish, we want to notifiy the hotel about the changes. The `unit_id` is not useful. It slows down the process to request reservation information.

**Comment by aprooks** [comment]
Hi,

yes at the moment we don't expose room's name via this endpoint since this is a list view and we try to minimize data send and queried. 

But we will consider adding more data to this list view, so thank you for a suggestion and provided use-case.

I have a couple of suggestions though. 
* caching Units seems reasonable since they change really rarely 
* instead of polling for reservations you might switch to use webhooks and be notified when reservation is created/updated. Afterward, you will still have to query a single reservation of interest via `GET /booking/v1/reservations/{id}` which will return you full information with most subresources prefilled. https://apaleo.com/push-it-webhooks-in-apaleo/

**Comment by aprooks** [comment]
@c2ofh a small update. We have an "expand" query parameter which will load unit details and give you unit names as well.

`https://api.apaleo.io/booking/v1/reservations?pageNumber=1&pageSize=100&expand=unit`

**Comment by c2ofh** [comment]
Thank you very much. This is great!
