### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by HotelDev** [apaleo/api#91]
## Question

When i call the refresh token api i get : 

`{
    "error": "invalid_grant"
}`

what could be the reason for this response ? 

![image](https://user-images.githubusercontent.com/48249687/53810349-688c9f00-3f5f-11e9-9c11-e0d486cde5fe.png)

## Background

we are only starting the integration process, i will also like to get some explanation on : 
1.  how ofter do we need to call the refresh token ? 
2. does the `authorization_code` need to be retrieve only once ? and after that we get the token and only need to refresh it ?

**Comment by pgrm** [comment]
hello, your client id is `KeezConnect` right? I think somebody forgot to give you offline access

**Comment by pgrm** [comment]
hello @HotelDev - instead of doing this manually, try using a library which will take care of it, there should be one in your preferred language. Those libraries should be capable to automatically refresh the token whenever it expires. The expiry time is in the token.

about the error, you get invalid_grant because the token you pass as a refresh token isn't a refresh token, it's an expired access token. A refresh token isn't a JWT it's a hash which the identity server recognizes.

You should include `offline_access` scope in your authorization request. That way you'll receive access token + refresh token. The access token is short lived and can be refreshed using the refresh token. But as I wrote before, probably there is a library out there in your favorite language, which can take care of all of that all by itself and you don't need to worry about it.

**Comment by HotelDev** [comment]
Hello Peter

Thank you, we can now use the refresh token.

another question : 

does the `authorization_code` is a one time code that can be store for later use after we get it ?
or there is a scenarios where we will need to fetch a new one ?

**Comment by pgrm** [comment]
@HotelDev I'm not sure I understand your question. `authorization_code` is used to refer to the grant type how you retrieve an access and refresh token. A refresh token is valid for ever, or until it's revoked. That one you should store securely. The access token is valid for a period of time which can change. The expiration time is written in the token, so you can read it to know how long it's valid.

At any given time, you can have as many access tokens around as you want. Generating a new access token won't invalidate the old one. We usually suggest to share the access token across multiple requests as long as it's feasible. It will be faster for your, because you won't need the extra round trip to the identity server. However, you shouldn't try to persist it. If you loose it because your service is restarted, or similar, you can always retrieve a new one.

Does this answer your question? Otherwise could you elaborate what you mean with `authorization_code` including maybe some examples? (don't post real tokens here on github)
