### ISSUE TITLE
Details about Finance Data

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#98]
## Question

We do not understand the logic of the invoice creation. We have two test bookings and we do not understand why they have different values for the field createInvoiceAction
1. Example: 
https://api.apaleo.com/finance/v1/invoices/preview?folioId=FQADYRZT-1-1
The value is "CreatesInvoiceAndClosesFolio"

2. Example: https://api.apaleo.com/finance/v1/invoices/preview?folioId=UTEPICJF-1-1
The value is "CannotCreateInvoice"

## Background

We are developing our own datawarehouse and are trying to understand the data in order to be able to evaluate if we need the information or not. We are using our own invoice tool since the apaleo invoicing is not matching our requirements.

**Comment by andreastubbe** [comment]
Invoices come with a couple of restrictions, legally. Whether you can create an invoice or not depends on whether the requirements are met, or not.
- the recipient address has to be complete, *unless* the hotel configured it differently in apaleo. Please check with them.
- an invoice was already created for the folio. Cannot have two invoices for one set of delivered services.
- not all charges from the folio have been posted, that means: they can still change. In this case, you would create an invoice for services which are to be delivered in the future, and they might still change (people change their reservations all the time). If that would happen, you would need to void the old invoice and create a new one (or create a correction) - but that's tough, as the guest probably already holds it in their hands, and you might not succeed in exchanging them. And then - the hotel's VAT and the one on the invoice don't match, and the Finanzamt will not be amused about that. It is theoretically possible to implement, but not supported by apaleo.
- this is a technical one: the invoice has pending payments. That can happen, when you trigger a credit card payment which goes all the way through the internet and back - between triggering the payment, and actually receiving an "okay!" we don't allow to do anything, really.

The field `CreateInvoiceWarning` in the response will tell you what the reason is.

**Comment by patrickHermannLimeHouse** [comment]
Ok, got it. Thank you!!
